/* Generated By:JJTree: Do not edit this line. ASTAddmonths.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package com.compuware.pmd.uniface.ast;

public class ASTAddmonths extends SimpleNode {
  public ASTAddmonths(int id) {
    super(id);
  }

  public ASTAddmonths(UnifaceParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UnifaceParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=149fbfb7c083d30c6b5a4625d422584a (do not edit this line) */
