/* Generated By:JJTree: Do not edit this line. ASTCommit.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package com.compuware.pmd.uniface.ast;

public class ASTCommit extends SimpleNode {
  public ASTCommit(int id) {
    super(id);
  }

  public ASTCommit(UnifaceParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UnifaceParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=279b0c85e9a25d27d18bef10fb693721 (do not edit this line) */
