/* Generated By:JJTree: Do not edit this line. ASTDisplaylength.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package com.compuware.pmd.uniface.ast;

public class ASTDisplaylength extends SimpleNode {
  public ASTDisplaylength(int id) {
    super(id);
  }

  public ASTDisplaylength(UnifaceParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UnifaceParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0f461bfbc03ce1f9918e416bc7eedf65 (do not edit this line) */
