/* Generated By:JJTree: Do not edit this line. ASTDeleteinstance.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package com.compuware.pmd.uniface.ast;

public class ASTDeleteinstance extends SimpleNode {
  public ASTDeleteinstance(int id) {
    super(id);
  }

  public ASTDeleteinstance(UnifaceParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UnifaceParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=01ff6b1228d79fae1999a8a10ffab141 (do not edit this line) */
