/* Generated By:JJTree: Do not edit this line. ASTDisplay.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package com.compuware.pmd.uniface.ast;

public class ASTDisplay extends SimpleNode {
  public ASTDisplay(int id) {
    super(id);
  }

  public ASTDisplay(UnifaceParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UnifaceParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5375f7d74e4829734036580d183cffff (do not edit this line) */
