/* Generated By:JJTree: Do not edit this line. ASTEntitycopy.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package com.compuware.pmd.uniface.ast;

public class ASTEntitycopy extends SimpleNode {
  public ASTEntitycopy(int id) {
    super(id);
  }

  public ASTEntitycopy(UnifaceParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UnifaceParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=92c70351a98442f32c48f72b5f15d14b (do not edit this line) */
