/* Generated By:JJTree: Do not edit this line. ASTExpressionList.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package com.compuware.pmd.uniface.ast;

public class ASTExpressionList extends SimpleNode {
  public ASTExpressionList(int id) {
    super(id);
  }

  public ASTExpressionList(UnifaceParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UnifaceParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=756635e081c5ea0c17e619eb84260a6a (do not edit this line) */
