/* Generated By:JJTree: Do not edit this line. ASTGoto.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package com.compuware.pmd.uniface.ast;

public class ASTGoto extends SimpleNode {
  public ASTGoto(int id) {
    super(id);
  }

  public ASTGoto(UnifaceParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UnifaceParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ded00c395979516c31d7bff6ef200bd5 (do not edit this line) */
