/* Generated By:JJTree: Do not edit this line. ASTInstruction.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package com.compuware.pmd.uniface.ast;

public class ASTInstruction extends SimpleNode {
  public ASTInstruction(int id) {
    super(id);
  }

  public ASTInstruction(UnifaceParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UnifaceParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d8d2cf7cf4926a965aa184e7776b7f4f (do not edit this line) */
