/* Generated By:JJTree: Do not edit this line. ASTIdentifierList.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package com.compuware.pmd.uniface.ast;

public class ASTIdentifierList extends SimpleNode {
  public ASTIdentifierList(int id) {
    super(id);
  }

  public ASTIdentifierList(UnifaceParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UnifaceParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e84a7ef4d21aee8e34efcc8fcad3eac4 (do not edit this line) */
