/* Generated By:JJTree: Do not edit this line. ASTLabelStatement.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package com.compuware.pmd.uniface.ast;

public class ASTLabelStatement extends SimpleNode {
  public ASTLabelStatement(int id) {
    super(id);
  }

  public ASTLabelStatement(UnifaceParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UnifaceParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e7e29c36841ccc3d2d3dac1cfd905013 (do not edit this line) */
