/* Generated By:JJTree: Do not edit this line. ASTLogicalExpression.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package com.compuware.pmd.uniface.ast;

public class ASTLogicalExpression extends SimpleNode {
  public ASTLogicalExpression(int id) {
    super(id);
  }

  public ASTLogicalExpression(UnifaceParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UnifaceParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=865be7ef55c36226f5775ecc87cfad65 (do not edit this line) */
