/* Generated By:JJTree: Do not edit this line. ASTOpen.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package com.compuware.pmd.uniface.ast;

public class ASTOpen extends SimpleNode {
  public ASTOpen(int id) {
    super(id);
  }

  public ASTOpen(UnifaceParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UnifaceParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bd604628e9bc4466216f89c298dc6ce9 (do not edit this line) */
