/* Generated By:JJTree: Do not edit this line. ASTRollback.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package com.compuware.pmd.uniface.ast;

public class ASTRollback extends SimpleNode {
  public ASTRollback(int id) {
    super(id);
  }

  public ASTRollback(UnifaceParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UnifaceParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b32c2e53547494b0da8a67413e3d41d7 (do not edit this line) */
