/* Generated By:JJTree: Do not edit this line. ASTReset.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package com.compuware.pmd.uniface.ast;

public class ASTReset extends SimpleNode {
  public ASTReset(int id) {
    super(id);
  }

  public ASTReset(UnifaceParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UnifaceParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2d2b9ff91ff8c990cc6faae09c5b6da9 (do not edit this line) */
