/* Generated By:JJTree: Do not edit this line. ASTRegister.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package com.compuware.pmd.uniface.ast;

public class ASTRegister extends SimpleNode {
  public ASTRegister(int id) {
    super(id);
  }

  public ASTRegister(UnifaceParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UnifaceParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=103f97594d8c1fa9aa814169f7be6a65 (do not edit this line) */
