/* Generated By:JJTree: Do not edit this line. ASTSelectCaseStatement.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package com.compuware.pmd.uniface.ast;

public class ASTSelectCaseStatement extends SimpleNode {
  public ASTSelectCaseStatement(int id) {
    super(id);
  }

  public ASTSelectCaseStatement(UnifaceParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UnifaceParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bf360b7862f0613aeb6488be746eec98 (do not edit this line) */
