/* Generated By:JJTree: Do not edit this line. ASTSetformfocus.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package com.compuware.pmd.uniface.ast;

public class ASTSetformfocus extends SimpleNode {
  public ASTSetformfocus(int id) {
    super(id);
  }

  public ASTSetformfocus(UnifaceParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UnifaceParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=289c86cad34e277bfcb73d46f33a20aa (do not edit this line) */
