/* Generated By:JJTree: Do not edit this line. ASTUppercase.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package com.compuware.pmd.uniface.ast;

public class ASTUppercase extends SimpleNode {
  public ASTUppercase(int id) {
    super(id);
  }

  public ASTUppercase(UnifaceParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UnifaceParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e2d3c89b9c68dc315f75cc7ad9864c0c (do not edit this line) */
