/* Generated By:JJTree: Do not edit this line. ASTVariableBlock.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package com.compuware.pmd.uniface.ast;

public class ASTVariableBlock extends SimpleNode {
  public ASTVariableBlock(int id) {
    super(id);
  }

  public ASTVariableBlock(UnifaceParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UnifaceParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a573f58d83c9205807cba266cd9c7ac5 (do not edit this line) */
