/* Generated By:JJTree: Do not edit this line. Node.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package com.compuware.pmd.uniface.ast;

/* All AST nodes must implement this interface.  It provides basic
   machinery for constructing the parent and child relationships
   between nodes. */

public interface Node extends net.sourceforge.pmd.ast.Node {

   /**
     * Accept the visitor. *
     */
    public Object jjtAccept(UnifaceParserVisitor visitor, Object data);
}
/* JavaCC - OriginalChecksum=3b3ed5ab7d5bc9168ada6ccff9e6f206 (do not edit this line) */
