/* Generated By:JavaCC: Do not edit this line. UnifaceParserTreeConstants.java Version 4.1 */
package com.compuware.pmd.uniface.ast;

public interface UnifaceParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTARGUMENT = 1;
  public int JJTEXPRESSION = 2;
  public int JJTCOMPILETIMECONSTANT = 3;
  public int JJTCONSTANT = 4;
  public int JJTEXPRESSIONLIST = 5;
  public int JJTLOGICALEXPRESSION = 6;
  public int JJTRELATIONALEXPRESSION = 7;
  public int JJTADDITIVEEXPRESSION = 8;
  public int JJTMULTIPLICATIVEEXPRESSION = 9;
  public int JJTUNARYEXPRESSION = 10;
  public int JJTUSERDEFINEDFUNCTION = 11;
  public int JJTSTRING = 12;
  public int JJTIDENTIFIER = 13;
  public int JJTREGISTER = 14;
  public int JJTGLOBALVARIABLE = 15;
  public int JJTCOMPONENTVARIABLE = 16;
  public int JJTIDENTIFIERLIST = 17;
  public int JJTINTEGER = 18;
  public int JJTDATATYPE = 19;
  public int JJTDIRECTION = 20;
  public int JJTVARIABLEDEFINITION = 21;
  public int JJTPARAMETER = 22;
  public int JJTPARAMETERBLOCK = 23;
  public int JJTVARIABLEBLOCK = 24;
  public int JJTCOMMENT = 25;
  public int JJTCOMMENTLINE = 26;
  public int JJTINSTRUCTION = 27;
  public int JJTPROCSTATEMENT = 28;
  public int JJTINDIRECTION = 29;
  public int JJTCOMPUTE = 30;
  public int JJTASSIGNMENT = 31;
  public int JJTFUNCTION = 32;
  public int JJTIFSTATEMENT = 33;
  public int JJTWHILESTATEMENT = 34;
  public int JJTREPEATSTATEMENT = 35;
  public int JJTSELECTCASESTATEMENT = 36;
  public int JJTLABELSTATEMENT = 37;
  public int JJTSTATEMENT = 38;
  public int JJTDELETEINSTANCE = 39;
  public int JJTNEWINSTANCE = 40;
  public int JJTSETFORMFOCUS = 41;
  public int JJTENTITYCOPY = 42;
  public int JJTADDMONTHS = 43;
  public int JJTCOMPARE = 44;
  public int JJTDISPLAYLENGTH = 45;
  public int JJTLENGTH = 46;
  public int JJTLOWERCASE = 47;
  public int JJTRESET = 48;
  public int JJTSCAN = 49;
  public int JJTSET = 50;
  public int JJTSTRIPATTRIBUTES = 51;
  public int JJTUPPERCASE = 52;
  public int JJTCLOSE = 53;
  public int JJTCOMMIT = 54;
  public int JJTOPEN = 55;
  public int JJTROLLBACK = 56;
  public int JJTSQL = 57;
  public int JJTACTIVATE = 58;
  public int JJTDISPLAY = 59;
  public int JJTGOTO = 60;
  public int JJTCLRMESS = 61;
  public int JJTDEBUG = 62;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "Argument",
    "Expression",
    "CompileTimeConstant",
    "Constant",
    "ExpressionList",
    "LogicalExpression",
    "RelationalExpression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "UserDefinedFunction",
    "String",
    "Identifier",
    "Register",
    "GlobalVariable",
    "ComponentVariable",
    "IdentifierList",
    "Integer",
    "Datatype",
    "Direction",
    "VariableDefinition",
    "Parameter",
    "ParameterBlock",
    "VariableBlock",
    "Comment",
    "CommentLine",
    "Instruction",
    "ProcStatement",
    "Indirection",
    "Compute",
    "Assignment",
    "Function",
    "IfStatement",
    "WhileStatement",
    "RepeatStatement",
    "SelectCaseStatement",
    "LabelStatement",
    "Statement",
    "Deleteinstance",
    "Newinstance",
    "Setformfocus",
    "Entitycopy",
    "Addmonths",
    "Compare",
    "Displaylength",
    "Length",
    "Lowercase",
    "Reset",
    "Scan",
    "Set",
    "Stripattributes",
    "Uppercase",
    "Close",
    "Commit",
    "Open",
    "Rollback",
    "Sql",
    "Activate",
    "Display",
    "Goto",
    "Clrmess",
    "Debug",
  };
}
/* JavaCC - OriginalChecksum=fb16dc0840ff1033cd88948150ab5b90 (do not edit this line) */
