/* Generated By:JJTree: Do not edit this line. ASTJspScriptlet.java */

package com.compuware.caqs.pmd.jsp.ast;

public class ASTJspScriptlet extends SimpleNode {
    public ASTJspScriptlet(int id) {
        super(id);
    }

    public ASTJspScriptlet(JspParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(JspParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
