/* Generated By:JJTree: Do not edit this line. ASTText.java */

package com.compuware.caqs.pmd.jsp.ast;

public class ASTText extends SimpleNode {
    public ASTText(int id) {
        super(id);
    }

    public ASTText(JspParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(JspParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
