/* Generated By:JJTree: Do not edit this line. Node.java */

package com.compuware.caqs.pmd.jsp.ast;

/* All AST nodes must implement this interface.  It provides basic
   machinery for constructing the parent and child relationships
   between nodes. */

public interface Node extends com.compuware.caqs.pmd.ast.Node {


    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(JspParserVisitor visitor, Object data);
}
