/**
 * UVCONNECTORPortType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package UVCONNECTOR.services.applic.uniface;

public interface UVCONNECTORPortType extends java.rmi.Remote {
    public void ADDPORTALPORTLET(ABSTRACTPORTLET.services.applic.uniface.ABSTRACTPORTLETType[] GENERATED_PARAMETER_NAME_1, java.lang.String PPACKAGEID, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, ABSTRACTPORTLET.services.applic.uniface.holders.ABSTRACTPORTLETArrayHolder GENERATED_PARAMETER_NAME_4, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_5) throws java.rmi.RemoteException;
    public void ADDPORTALUSER(ABSTRACTPORTAL_USER.services.applic.uniface.ABSTRACTPORTAL_USERType[] GENERATED_PARAMETER_NAME_1, java.lang.String PPACKAGEID, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException;
    public void AUTHENTICATEPORTALUSER(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PUSERID, java.lang.String PPASSWORD, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, STANDARDCOOKIE_CONTEXT.services.applic.uniface.holders.STANDARDCOOKIE_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.BooleanHolder PISAUTHENTICATED) throws java.rmi.RemoteException;
    public void AUTHENTICATEUSER(java.lang.String PUSERID, java.lang.String PPASSWORD, javax.xml.rpc.holders.IntHolder _return, STANDARDSECURITY_CONTEXT.services.applic.uniface.holders.STANDARDSECURITY_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_1, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, javax.xml.rpc.holders.BooleanHolder PISAUTHENTICATED) throws java.rmi.RemoteException;
    public void CHKTOKENACCESS(java.lang.String PTOKEN, java.lang.String PACCESSKEY, java.lang.String PACCESSKEYTYPE, javax.xml.rpc.holders.IntHolder _return, javax.xml.rpc.holders.StringHolder PHASACCESS) throws java.rmi.RemoteException;
    public void DECODESTRING(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PINSTRING, javax.xml.rpc.holders.IntHolder _return, javax.xml.rpc.holders.StringHolder POUTSTRING) throws java.rmi.RemoteException;
    public void DECRYPTSTRING(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PINSTRING, javax.xml.rpc.holders.IntHolder _return, javax.xml.rpc.holders.StringHolder POUTSTRING) throws java.rmi.RemoteException;
    public void DELETEDOMAIN(java.lang.String PDOMAINID, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_2, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_3) throws java.rmi.RemoteException;
    public void DELETEDOMAINMEMBERSHIP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PGROUPID, java.lang.String PMEMBERSHIPID, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2) throws java.rmi.RemoteException;
    public void DELETEGROUP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PGROUPID, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2) throws java.rmi.RemoteException;
    public void DELETEGROUPPACKAGE(java.lang.String PID, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_2, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_3) throws java.rmi.RemoteException;
    public void DELETEPACKAGEMEMBERSHIP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PMEMBERSHIPID, java.lang.String PGROUPID, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2) throws java.rmi.RemoteException;
    public void DELETEPAGEMEMBERSHIP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PMEMBERSHIPID, java.lang.String PGROUPID, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2) throws java.rmi.RemoteException;
    public void DELETEPORTALPAGE(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PPAGEID, java.lang.String PPAGETYPE, java.lang.String POWNERID, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2) throws java.rmi.RemoteException;
    public void DELETEPORTALPAGEPORTLET(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PPAGEID, java.lang.String PPORTLETID, java.lang.String PPAGETYPE, java.lang.String POWNERID, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2) throws java.rmi.RemoteException;
    public void DELETEPORTLET(java.lang.String PPORTLETID, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_2, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_3) throws java.rmi.RemoteException;
    public void DELETEPORTLETCATEGORY(java.lang.String PID, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_2, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_3) throws java.rmi.RemoteException;
    public void DELETEPORTLETDOMAINMEMBERSHIP(java.lang.String PDOMAINID, java.lang.String PPORTLETID, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException;
    public void DELETEPORTLETMEMBERSHIP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PMEMBERSHIPID, java.lang.String PGROUPID, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2) throws java.rmi.RemoteException;
    public void DELETEUSER(java.lang.String PUSERID, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_2, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_3) throws java.rmi.RemoteException;
    public void DELETEUSERMEMBERSHIP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PMEMBERSHIPID, java.lang.String PGROUPID, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2) throws java.rmi.RemoteException;
    public void ENCODESTRING(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PINSTRING, javax.xml.rpc.holders.IntHolder _return, javax.xml.rpc.holders.StringHolder POUTSTRING) throws java.rmi.RemoteException;
    public void ENCRYPTSTRING(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PINSTRING, javax.xml.rpc.holders.IntHolder _return, javax.xml.rpc.holders.StringHolder POUTSTRING) throws java.rmi.RemoteException;
    public void GETPAGENAVIGATION(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PUSERID, java.lang.String POPTIONS, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, ABSTRACTPAGE_NAVIGATION.services.applic.uniface.holders.ABSTRACTPAGE_NAVIGATIONArrayHolder GENERATED_PARAMETER_NAME_3, ABSTRACTPAGE_NAVIGATION.services.applic.uniface.holders.ABSTRACTPAGE_NAVIGATIONArrayHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException;
    public void GETPORTALFOOTER(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String POPTIONS, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, ABSTRACTFOOTER.services.applic.uniface.holders.ABSTRACTFOOTERTypeHolder GENERATED_PARAMETER_NAME_3, ABSTRACTFOOTER_LINK.services.applic.uniface.holders.ABSTRACTFOOTER_LINKArrayHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException;
    public void GETPORTALINFO(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PMENUBARFILTER, java.lang.String PMENUFILTER, java.lang.String PMENUITEMFILTER, java.lang.String POPTIONS, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, ABSTRACTPORTAL_PARAM_CONFIG.services.applic.uniface.holders.ABSTRACTPORTAL_PARAM_CONFIGArrayHolder GENERATED_PARAMETER_NAME_3, ABSTRACTPORTAL_IMAGE_CONFIG.services.applic.uniface.holders.ABSTRACTPORTAL_IMAGE_CONFIGArrayHolder GENERATED_PARAMETER_NAME_4, ABSTRACTPORTAL_MESSAGE_CONFIG.services.applic.uniface.holders.ABSTRACTPORTAL_MESSAGE_CONFIGArrayHolder GENERATED_PARAMETER_NAME_5, ABSTRACTMENU_BAR.services.applic.uniface.holders.ABSTRACTMENU_BARArrayHolder GENERATED_PARAMETER_NAME_6, ABSTRACTMENU.services.applic.uniface.holders.ABSTRACTMENUArrayHolder GENERATED_PARAMETER_NAME_7, ABSTRACTMENU_ITEM.services.applic.uniface.holders.ABSTRACTMENU_ITEMArrayHolder GENERATED_PARAMETER_NAME_8, ABSTRACTFOOTER.services.applic.uniface.holders.ABSTRACTFOOTERTypeHolder GENERATED_PARAMETER_NAME_9, ABSTRACTFOOTER_LINK.services.applic.uniface.holders.ABSTRACTFOOTER_LINKArrayHolder GENERATED_PARAMETER_NAME_10) throws java.rmi.RemoteException;
    public void GETPORTALMENU(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PMENUBARFILTER, java.lang.String PMENUFILTER, java.lang.String PMENUITEMFILTER, java.lang.String POPTIONS, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, ABSTRACTMENU_BAR.services.applic.uniface.holders.ABSTRACTMENU_BARArrayHolder GENERATED_PARAMETER_NAME_3, ABSTRACTMENU.services.applic.uniface.holders.ABSTRACTMENUArrayHolder GENERATED_PARAMETER_NAME_4, ABSTRACTMENU_ITEM.services.applic.uniface.holders.ABSTRACTMENU_ITEMArrayHolder GENERATED_PARAMETER_NAME_5) throws java.rmi.RemoteException;
    public void GETPORTALPAGE(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PUSERID, javax.xml.rpc.holders.StringHolder PCURRENTPAGEID, javax.xml.rpc.holders.StringHolder PCURRENTPAGETYPE, java.lang.String POPTIONS, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, ABSTRACTPORTAL_PAGE_VIEW.services.applic.uniface.holders.ABSTRACTPORTAL_PAGE_VIEWTypeHolder GENERATED_PARAMETER_NAME_3, ABSTRACTPORTAL_PAGE_PORTLET_VIEW.services.applic.uniface.holders.ABSTRACTPORTAL_PAGE_PORTLET_VIEWArrayHolder GENERATED_PARAMETER_NAME_4, ABSTRACTPAGE_NAVIGATION.services.applic.uniface.holders.ABSTRACTPAGE_NAVIGATIONArrayHolder GENERATED_PARAMETER_NAME_5, ABSTRACTPAGE_NAVIGATION.services.applic.uniface.holders.ABSTRACTPAGE_NAVIGATIONArrayHolder GENERATED_PARAMETER_NAME_6) throws java.rmi.RemoteException;
    public void GETPORTLETCONTENT(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PPORTLETID, java.lang.String PUSERID, java.lang.String POPTIONS, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, javax.xml.rpc.holders.StringHolder PCONTENT) throws java.rmi.RemoteException;
    public void GETUSERIDFROMTOKEN(java.lang.String PTOKEN, javax.xml.rpc.holders.IntHolder _return, javax.xml.rpc.holders.StringHolder PUSERID, javax.xml.rpc.holders.StringHolder PTIMESTAMP) throws java.rmi.RemoteException;
    public void INSERTDOMAIN(ABSTRACTPORTAL_DOMAIN.services.applic.uniface.ABSTRACTPORTAL_DOMAINType[] GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_2, javax.xml.rpc.holders.IntHolder _return, ABSTRACTPORTAL_DOMAIN.services.applic.uniface.holders.ABSTRACTPORTAL_DOMAINArrayHolder GENERATED_PARAMETER_NAME_3, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException;
    public void INSERTDOMAINMEMBERSHIP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTGROUP_MEMBERSHIP.services.applic.uniface.ABSTRACTGROUP_MEMBERSHIPType[] GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2) throws java.rmi.RemoteException;
    public void INSERTGROUP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTGROUP.services.applic.uniface.ABSTRACTGROUPType[] GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, ABSTRACTGROUP.services.applic.uniface.holders.ABSTRACTGROUPArrayHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException;
    public void INSERTGROUPPACKAGE(ABSTRACTGROUP_PACKAGE.services.applic.uniface.ABSTRACTGROUP_PACKAGEType[] GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_2, javax.xml.rpc.holders.IntHolder _return, ABSTRACTGROUP_PACKAGE.services.applic.uniface.holders.ABSTRACTGROUP_PACKAGEArrayHolder GENERATED_PARAMETER_NAME_3, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException;
    public void INSERTPACKAGEMEMBERSHIP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTGROUP_MEMBERSHIP.services.applic.uniface.ABSTRACTGROUP_MEMBERSHIPType[] GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2) throws java.rmi.RemoteException;
    public void INSERTPAGEMEMBERSHIP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTGROUP_MEMBERSHIP.services.applic.uniface.ABSTRACTGROUP_MEMBERSHIPType[] GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2) throws java.rmi.RemoteException;
    public void INSERTPORTALPAGE(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTPORTAL_PAGE.services.applic.uniface.ABSTRACTPORTAL_PAGEType[] GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, ABSTRACTPORTAL_PAGE.services.applic.uniface.holders.ABSTRACTPORTAL_PAGEArrayHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException;
    public void INSERTPORTALPAGEPORTLET(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTPORTAL_PAGE_PORTLET.services.applic.uniface.ABSTRACTPORTAL_PAGE_PORTLETType[] GENERATED_PARAMETER_NAME_3, java.lang.String PPAGETYPE, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2) throws java.rmi.RemoteException;
    public void INSERTPORTLETCATEGORY(ABSTRACTPORTLET_CATEGORY.services.applic.uniface.ABSTRACTPORTLET_CATEGORYType[] GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_2, javax.xml.rpc.holders.IntHolder _return, ABSTRACTPORTLET_CATEGORY.services.applic.uniface.holders.ABSTRACTPORTLET_CATEGORYArrayHolder GENERATED_PARAMETER_NAME_3, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException;
    public void INSERTPORTLETDOMAINMEMBERSHIP(ABSTRACTGROUP_MEMBERSHIP.services.applic.uniface.ABSTRACTGROUP_MEMBERSHIPType[] GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_2, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_3) throws java.rmi.RemoteException;
    public void INSERTPORTLETMEMBERSHIP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTGROUP_MEMBERSHIP.services.applic.uniface.ABSTRACTGROUP_MEMBERSHIPType[] GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2) throws java.rmi.RemoteException;
    public void INSERTUSERMEMBERSHIP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTPORTAL_USER_MEMBERSHIP.services.applic.uniface.ABSTRACTPORTAL_USER_MEMBERSHIPType[] GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2) throws java.rmi.RemoteException;
    public void SELECTDOMAIN(ABSTRACTPORTAL_DOMAIN.services.applic.uniface.ABSTRACTPORTAL_DOMAINType GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, ABSTRACTPORTAL_DOMAIN.services.applic.uniface.holders.ABSTRACTPORTAL_DOMAINArrayHolder GENERATED_PARAMETER_NAME_2, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException;
    public void SELECTDOMAINMEMBERSHIP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTGROUP_MEMBERSHIP.services.applic.uniface.ABSTRACTGROUP_MEMBERSHIPType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, ABSTRACTGROUP_MEMBERSHIP.services.applic.uniface.holders.ABSTRACTGROUP_MEMBERSHIPArrayHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException;
    public void SELECTFILTERDOMAIN(ABSTRACTPORTAL_DOMAIN.services.applic.uniface.ABSTRACTPORTAL_DOMAINType GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, ABSTRACTPORTAL_DOMAIN.services.applic.uniface.holders.ABSTRACTPORTAL_DOMAINArrayHolder GENERATED_PARAMETER_NAME_2, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException;
    public void SELECTFILTERGROUP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTGROUP.services.applic.uniface.ABSTRACTGROUPType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, ABSTRACTGROUP.services.applic.uniface.holders.ABSTRACTGROUPArrayHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException;
    public void SELECTFILTERGROUPPACKAGE(ABSTRACTGROUP_PACKAGE.services.applic.uniface.ABSTRACTGROUP_PACKAGEType GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, ABSTRACTGROUP_PACKAGE.services.applic.uniface.holders.ABSTRACTGROUP_PACKAGEArrayHolder GENERATED_PARAMETER_NAME_2, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException;
    public void SELECTFILTERPACKAGEMEMBERSHIP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTGROUP_MEMBERSHIP.services.applic.uniface.ABSTRACTGROUP_MEMBERSHIPType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, ABSTRACTGROUP_MEMBERSHIP.services.applic.uniface.holders.ABSTRACTGROUP_MEMBERSHIPArrayHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException;
    public void SELECTFILTERPORTALPAGE(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTPORTAL_PAGE.services.applic.uniface.ABSTRACTPORTAL_PAGEType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, ABSTRACTPORTAL_PAGE.services.applic.uniface.holders.ABSTRACTPORTAL_PAGEArrayHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException;
    public void SELECTFILTERPORTALPORTLET(ABSTRACTPORTLET.services.applic.uniface.ABSTRACTPORTLETType GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, ABSTRACTPORTLET.services.applic.uniface.holders.ABSTRACTPORTLETArrayHolder GENERATED_PARAMETER_NAME_2, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException;
    public void SELECTFILTERPORTLET(ABSTRACTPORTLET.services.applic.uniface.ABSTRACTPORTLETType GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, ABSTRACTPORTLET.services.applic.uniface.holders.ABSTRACTPORTLETArrayHolder GENERATED_PARAMETER_NAME_2, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException;
    public void SELECTFILTERPORTLETBYUSER(ABSTRACTPORTLET.services.applic.uniface.ABSTRACTPORTLETType GENERATED_PARAMETER_NAME_2, java.lang.String PUSERID, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_4, javax.xml.rpc.holders.IntHolder _return, ABSTRACTPORTLET.services.applic.uniface.holders.ABSTRACTPORTLETArrayHolder GENERATED_PARAMETER_NAME_3, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_5) throws java.rmi.RemoteException;
    public void SELECTFILTERPORTLETCATEGORY(ABSTRACTPORTLET_CATEGORY.services.applic.uniface.ABSTRACTPORTLET_CATEGORYType GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, ABSTRACTPORTLET_CATEGORY.services.applic.uniface.holders.ABSTRACTPORTLET_CATEGORYArrayHolder GENERATED_PARAMETER_NAME_2, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException;
    public void SELECTFILTERUSER(ABSTRACTPORTAL_USER.services.applic.uniface.ABSTRACTPORTAL_USERType GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, ABSTRACTPORTAL_USER.services.applic.uniface.holders.ABSTRACTPORTAL_USERArrayHolder GENERATED_PARAMETER_NAME_2, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException;
    public void SELECTGROUP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTGROUP.services.applic.uniface.ABSTRACTGROUPType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, ABSTRACTGROUP.services.applic.uniface.holders.ABSTRACTGROUPArrayHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException;
    public void SELECTGROUPPACKAGE(ABSTRACTGROUP_PACKAGE.services.applic.uniface.ABSTRACTGROUP_PACKAGEType GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, ABSTRACTGROUP_PACKAGE.services.applic.uniface.holders.ABSTRACTGROUP_PACKAGEArrayHolder GENERATED_PARAMETER_NAME_2, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException;
    public void SELECTHTMLPORTLETCONTENT(java.lang.String PUSERID, java.lang.String PPORTLETID, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, ABSTRACTHTML_PORTLET_PROPERTY.services.applic.uniface.holders.ABSTRACTHTML_PORTLET_PROPERTYTypeHolder GENERATED_PARAMETER_NAME_4, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_5) throws java.rmi.RemoteException;
    public void SELECTJOBDETAIL(ABSTRACTJOB_DETAIL.services.applic.uniface.ABSTRACTJOB_DETAILType GENERATED_PARAMETER_NAME_1, javax.xml.rpc.holders.IntHolder _return, ABSTRACTJOB_DETAIL.services.applic.uniface.holders.ABSTRACTJOB_DETAILArrayHolder GENERATED_PARAMETER_NAME_2, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_3) throws java.rmi.RemoteException;
    public void SELECTJOBTRIGGER(ABSTRACTJOB_TRIGGER.services.applic.uniface.ABSTRACTJOB_TRIGGERType GENERATED_PARAMETER_NAME_1, javax.xml.rpc.holders.IntHolder _return, ABSTRACTJOB_TRIGGER.services.applic.uniface.holders.ABSTRACTJOB_TRIGGERArrayHolder GENERATED_PARAMETER_NAME_2, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_3) throws java.rmi.RemoteException;
    public void SELECTPACKAGEMEMBERSHIP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTGROUP_MEMBERSHIP.services.applic.uniface.ABSTRACTGROUP_MEMBERSHIPType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, ABSTRACTGROUP_MEMBERSHIP.services.applic.uniface.holders.ABSTRACTGROUP_MEMBERSHIPArrayHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException;
    public void SELECTPAGEMEMBERSHIP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTGROUP_MEMBERSHIP.services.applic.uniface.ABSTRACTGROUP_MEMBERSHIPType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, ABSTRACTGROUP_MEMBERSHIP.services.applic.uniface.holders.ABSTRACTGROUP_MEMBERSHIPArrayHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException;
    public void SELECTPORTALPAGE(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTPORTAL_PAGE.services.applic.uniface.ABSTRACTPORTAL_PAGEType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, ABSTRACTPORTAL_PAGE.services.applic.uniface.holders.ABSTRACTPORTAL_PAGEArrayHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException;
    public void SELECTPORTALPAGEPORTLET(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTPORTAL_PAGE_PORTLET.services.applic.uniface.ABSTRACTPORTAL_PAGE_PORTLETType GENERATED_PARAMETER_NAME_3, java.lang.String PPAGETYPE, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, ABSTRACTPORTAL_PAGE_PORTLET.services.applic.uniface.holders.ABSTRACTPORTAL_PAGE_PORTLETArrayHolder GENERATED_PARAMETER_NAME_5) throws java.rmi.RemoteException;
    public void SELECTPORTALPORTLET(ABSTRACTPORTLET.services.applic.uniface.ABSTRACTPORTLETType GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, ABSTRACTPORTLET.services.applic.uniface.holders.ABSTRACTPORTLETArrayHolder GENERATED_PARAMETER_NAME_2, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException;
    public void SELECTPORTLET(ABSTRACTPORTLET.services.applic.uniface.ABSTRACTPORTLETType GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, ABSTRACTPORTLET.services.applic.uniface.holders.ABSTRACTPORTLETArrayHolder GENERATED_PARAMETER_NAME_2, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException;
    public void SELECTPORTLETCATEGORY(ABSTRACTPORTLET_CATEGORY.services.applic.uniface.ABSTRACTPORTLET_CATEGORYType GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, ABSTRACTPORTLET_CATEGORY.services.applic.uniface.holders.ABSTRACTPORTLET_CATEGORYArrayHolder GENERATED_PARAMETER_NAME_2, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException;
    public void SELECTPORTLETDOMAINMEMBERSHIP(ABSTRACTGROUP_MEMBERSHIP.services.applic.uniface.ABSTRACTGROUP_MEMBERSHIPType GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, ABSTRACTGROUP_MEMBERSHIP.services.applic.uniface.holders.ABSTRACTGROUP_MEMBERSHIPArrayHolder GENERATED_PARAMETER_NAME_2, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException;
    public void SELECTPORTLETMEMBERSHIP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTGROUP_MEMBERSHIP.services.applic.uniface.ABSTRACTGROUP_MEMBERSHIPType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, ABSTRACTGROUP_MEMBERSHIP.services.applic.uniface.holders.ABSTRACTGROUP_MEMBERSHIPArrayHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException;
    public void SELECTTEXTPORTLETCONTENT(java.lang.String PUSERID, java.lang.String PPORTLETID, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, ABSTRACTHTML_PORTLET_PROPERTY.services.applic.uniface.holders.ABSTRACTHTML_PORTLET_PROPERTYTypeHolder GENERATED_PARAMETER_NAME_4, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_5) throws java.rmi.RemoteException;
    public void SELECTUSER(ABSTRACTPORTAL_USER.services.applic.uniface.ABSTRACTPORTAL_USERType GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, ABSTRACTPORTAL_USER.services.applic.uniface.holders.ABSTRACTPORTAL_USERArrayHolder GENERATED_PARAMETER_NAME_2, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException;
    public void SELECTUSERMEMBERSHIP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTPORTAL_USER_MEMBERSHIP.services.applic.uniface.ABSTRACTPORTAL_USER_MEMBERSHIPType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, ABSTRACTPORTAL_USER_MEMBERSHIP.services.applic.uniface.holders.ABSTRACTPORTAL_USER_MEMBERSHIPArrayHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException;
    public void UPDATEDOMAIN(ABSTRACTPORTAL_DOMAIN.services.applic.uniface.ABSTRACTPORTAL_DOMAINType[] GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_2, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_3) throws java.rmi.RemoteException;
    public void UPDATEGROUP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTGROUP.services.applic.uniface.ABSTRACTGROUPType[] GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2) throws java.rmi.RemoteException;
    public void UPDATEGROUPPACKAGE(ABSTRACTGROUP_PACKAGE.services.applic.uniface.ABSTRACTGROUP_PACKAGEType[] GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_2, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_3) throws java.rmi.RemoteException;
    public void UPDATEHTMLPORTLETCONTENT(java.lang.String PUSERID, java.lang.String PPORTLETID, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, ABSTRACTHTML_PORTLET_PROPERTY.services.applic.uniface.ABSTRACTHTML_PORTLET_PROPERTYType GENERATED_PARAMETER_NAME_4, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_5) throws java.rmi.RemoteException;
    public void UPDATEPORTALPAGE(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTPORTAL_PAGE.services.applic.uniface.ABSTRACTPORTAL_PAGEType[] GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2) throws java.rmi.RemoteException;
    public void UPDATEPORTLET(ABSTRACTPORTLET.services.applic.uniface.ABSTRACTPORTLETType[] GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_2, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_3) throws java.rmi.RemoteException;
    public void UPDATEPORTLETCATEGORY(ABSTRACTPORTLET_CATEGORY.services.applic.uniface.ABSTRACTPORTLET_CATEGORYType[] GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_2, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_3) throws java.rmi.RemoteException;
    public void UPDATETEXTPORTLETCONTENT(java.lang.String PUSERID, java.lang.String PPORTLETID, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, ABSTRACTHTML_PORTLET_PROPERTY.services.applic.uniface.ABSTRACTHTML_PORTLET_PROPERTYType GENERATED_PARAMETER_NAME_4, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_5) throws java.rmi.RemoteException;
    public void UPDATEUSER(ABSTRACTPORTAL_USER.services.applic.uniface.ABSTRACTPORTAL_USERType[] GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_2, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_3) throws java.rmi.RemoteException;
    public void UPDATEUSERPASSWORD(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PUSERID, java.lang.String PPASSWORD, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException;
    public void VALIDATEPORTALUSER(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, STANDARDCOOKIE_CONTEXT.services.applic.uniface.STANDARDCOOKIE_CONTEXTType GENERATED_PARAMETER_NAME_2, javax.xml.rpc.holders.IntHolder _return, javax.xml.rpc.holders.StringHolder PUSERID, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4, STANDARDCOOKIE_CONTEXT.services.applic.uniface.holders.STANDARDCOOKIE_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_5, javax.xml.rpc.holders.BooleanHolder PISVALIDATED) throws java.rmi.RemoteException;
    public void VALIDATEUSER(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, javax.xml.rpc.holders.BooleanHolder PISVALIDATED) throws java.rmi.RemoteException;
}
