package UVCONNECTOR.services.applic.uniface;

public class UVCONNECTORPortTypeProxy implements UVCONNECTOR.services.applic.uniface.UVCONNECTORPortType {
  private String _endpoint = null;
  private UVCONNECTOR.services.applic.uniface.UVCONNECTORPortType uVCONNECTORPortType = null;
  
  public UVCONNECTORPortTypeProxy() {
    _initUVCONNECTORPortTypeProxy();
  }
  
  public UVCONNECTORPortTypeProxy(String endpoint) {
    _endpoint = endpoint;
    _initUVCONNECTORPortTypeProxy();
  }
  
  private void _initUVCONNECTORPortTypeProxy() {
    try {
      uVCONNECTORPortType = (new UVCONNECTOR.services.applic.uniface.UVCONNECTORServiceLocator()).getUVCONNECTOR();
      if (uVCONNECTORPortType != null) {
        if (_endpoint != null)
          ((javax.xml.rpc.Stub)uVCONNECTORPortType)._setProperty("javax.xml.rpc.service.endpoint.address", _endpoint);
        else
          _endpoint = (String)((javax.xml.rpc.Stub)uVCONNECTORPortType)._getProperty("javax.xml.rpc.service.endpoint.address");
      }
      
    }
    catch (javax.xml.rpc.ServiceException serviceException) {}
  }
  
  public String getEndpoint() {
    return _endpoint;
  }
  
  public void setEndpoint(String endpoint) {
    _endpoint = endpoint;
    if (uVCONNECTORPortType != null)
      ((javax.xml.rpc.Stub)uVCONNECTORPortType)._setProperty("javax.xml.rpc.service.endpoint.address", _endpoint);
    
  }
  
  public UVCONNECTOR.services.applic.uniface.UVCONNECTORPortType getUVCONNECTORPortType() {
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    return uVCONNECTORPortType;
  }
  
  public void ADDPORTALPORTLET(ABSTRACTPORTLET.services.applic.uniface.ABSTRACTPORTLETType[] GENERATED_PARAMETER_NAME_1, java.lang.String PPACKAGEID, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, ABSTRACTPORTLET.services.applic.uniface.holders.ABSTRACTPORTLETArrayHolder GENERATED_PARAMETER_NAME_4, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_5) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.ADDPORTALPORTLET(GENERATED_PARAMETER_NAME_1, PPACKAGEID, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_4, GENERATED_PARAMETER_NAME_5);
  }
  
  public void ADDPORTALUSER(ABSTRACTPORTAL_USER.services.applic.uniface.ABSTRACTPORTAL_USERType[] GENERATED_PARAMETER_NAME_1, java.lang.String PPACKAGEID, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.ADDPORTALUSER(GENERATED_PARAMETER_NAME_1, PPACKAGEID, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_4);
  }
  
  public void AUTHENTICATEPORTALUSER(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PUSERID, java.lang.String PPASSWORD, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, STANDARDCOOKIE_CONTEXT.services.applic.uniface.holders.STANDARDCOOKIE_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.BooleanHolder PISAUTHENTICATED) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.AUTHENTICATEPORTALUSER(GENERATED_PARAMETER_NAME_1, PUSERID, PPASSWORD, _return, GENERATED_PARAMETER_NAME_2, GENERATED_PARAMETER_NAME_3, PISAUTHENTICATED);
  }
  
  public void AUTHENTICATEUSER(java.lang.String PUSERID, java.lang.String PPASSWORD, javax.xml.rpc.holders.IntHolder _return, STANDARDSECURITY_CONTEXT.services.applic.uniface.holders.STANDARDSECURITY_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_1, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, javax.xml.rpc.holders.BooleanHolder PISAUTHENTICATED) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.AUTHENTICATEUSER(PUSERID, PPASSWORD, _return, GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_2, PISAUTHENTICATED);
  }
  
  public void CHKTOKENACCESS(java.lang.String PTOKEN, java.lang.String PACCESSKEY, java.lang.String PACCESSKEYTYPE, javax.xml.rpc.holders.IntHolder _return, javax.xml.rpc.holders.StringHolder PHASACCESS) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.CHKTOKENACCESS(PTOKEN, PACCESSKEY, PACCESSKEYTYPE, _return, PHASACCESS);
  }
  
  public void DECODESTRING(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PINSTRING, javax.xml.rpc.holders.IntHolder _return, javax.xml.rpc.holders.StringHolder POUTSTRING) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.DECODESTRING(GENERATED_PARAMETER_NAME_1, PINSTRING, _return, POUTSTRING);
  }
  
  public void DECRYPTSTRING(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PINSTRING, javax.xml.rpc.holders.IntHolder _return, javax.xml.rpc.holders.StringHolder POUTSTRING) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.DECRYPTSTRING(GENERATED_PARAMETER_NAME_1, PINSTRING, _return, POUTSTRING);
  }
  
  public void DELETEDOMAIN(java.lang.String PDOMAINID, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_2, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_3) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.DELETEDOMAIN(PDOMAINID, GENERATED_PARAMETER_NAME_2, _return, GENERATED_PARAMETER_NAME_3);
  }
  
  public void DELETEDOMAINMEMBERSHIP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PGROUPID, java.lang.String PMEMBERSHIPID, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.DELETEDOMAINMEMBERSHIP(GENERATED_PARAMETER_NAME_1, PGROUPID, PMEMBERSHIPID, _return, GENERATED_PARAMETER_NAME_2);
  }
  
  public void DELETEGROUP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PGROUPID, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.DELETEGROUP(GENERATED_PARAMETER_NAME_1, PGROUPID, _return, GENERATED_PARAMETER_NAME_2);
  }
  
  public void DELETEGROUPPACKAGE(java.lang.String PID, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_2, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_3) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.DELETEGROUPPACKAGE(PID, GENERATED_PARAMETER_NAME_2, _return, GENERATED_PARAMETER_NAME_3);
  }
  
  public void DELETEPACKAGEMEMBERSHIP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PMEMBERSHIPID, java.lang.String PGROUPID, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.DELETEPACKAGEMEMBERSHIP(GENERATED_PARAMETER_NAME_1, PMEMBERSHIPID, PGROUPID, _return, GENERATED_PARAMETER_NAME_2);
  }
  
  public void DELETEPAGEMEMBERSHIP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PMEMBERSHIPID, java.lang.String PGROUPID, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.DELETEPAGEMEMBERSHIP(GENERATED_PARAMETER_NAME_1, PMEMBERSHIPID, PGROUPID, _return, GENERATED_PARAMETER_NAME_2);
  }
  
  public void DELETEPORTALPAGE(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PPAGEID, java.lang.String PPAGETYPE, java.lang.String POWNERID, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.DELETEPORTALPAGE(GENERATED_PARAMETER_NAME_1, PPAGEID, PPAGETYPE, POWNERID, _return, GENERATED_PARAMETER_NAME_2);
  }
  
  public void DELETEPORTALPAGEPORTLET(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PPAGEID, java.lang.String PPORTLETID, java.lang.String PPAGETYPE, java.lang.String POWNERID, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.DELETEPORTALPAGEPORTLET(GENERATED_PARAMETER_NAME_1, PPAGEID, PPORTLETID, PPAGETYPE, POWNERID, _return, GENERATED_PARAMETER_NAME_2);
  }
  
  public void DELETEPORTLET(java.lang.String PPORTLETID, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_2, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_3) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.DELETEPORTLET(PPORTLETID, GENERATED_PARAMETER_NAME_2, _return, GENERATED_PARAMETER_NAME_3);
  }
  
  public void DELETEPORTLETCATEGORY(java.lang.String PID, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_2, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_3) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.DELETEPORTLETCATEGORY(PID, GENERATED_PARAMETER_NAME_2, _return, GENERATED_PARAMETER_NAME_3);
  }
  
  public void DELETEPORTLETDOMAINMEMBERSHIP(java.lang.String PDOMAINID, java.lang.String PPORTLETID, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.DELETEPORTLETDOMAINMEMBERSHIP(PDOMAINID, PPORTLETID, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_4);
  }
  
  public void DELETEPORTLETMEMBERSHIP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PMEMBERSHIPID, java.lang.String PGROUPID, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.DELETEPORTLETMEMBERSHIP(GENERATED_PARAMETER_NAME_1, PMEMBERSHIPID, PGROUPID, _return, GENERATED_PARAMETER_NAME_2);
  }
  
  public void DELETEUSER(java.lang.String PUSERID, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_2, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_3) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.DELETEUSER(PUSERID, GENERATED_PARAMETER_NAME_2, _return, GENERATED_PARAMETER_NAME_3);
  }
  
  public void DELETEUSERMEMBERSHIP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PMEMBERSHIPID, java.lang.String PGROUPID, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.DELETEUSERMEMBERSHIP(GENERATED_PARAMETER_NAME_1, PMEMBERSHIPID, PGROUPID, _return, GENERATED_PARAMETER_NAME_2);
  }
  
  public void ENCODESTRING(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PINSTRING, javax.xml.rpc.holders.IntHolder _return, javax.xml.rpc.holders.StringHolder POUTSTRING) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.ENCODESTRING(GENERATED_PARAMETER_NAME_1, PINSTRING, _return, POUTSTRING);
  }
  
  public void ENCRYPTSTRING(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PINSTRING, javax.xml.rpc.holders.IntHolder _return, javax.xml.rpc.holders.StringHolder POUTSTRING) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.ENCRYPTSTRING(GENERATED_PARAMETER_NAME_1, PINSTRING, _return, POUTSTRING);
  }
  
  public void GETPAGENAVIGATION(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PUSERID, java.lang.String POPTIONS, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, ABSTRACTPAGE_NAVIGATION.services.applic.uniface.holders.ABSTRACTPAGE_NAVIGATIONArrayHolder GENERATED_PARAMETER_NAME_3, ABSTRACTPAGE_NAVIGATION.services.applic.uniface.holders.ABSTRACTPAGE_NAVIGATIONArrayHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.GETPAGENAVIGATION(GENERATED_PARAMETER_NAME_1, PUSERID, POPTIONS, _return, GENERATED_PARAMETER_NAME_2, GENERATED_PARAMETER_NAME_3, GENERATED_PARAMETER_NAME_4);
  }
  
  public void GETPORTALFOOTER(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String POPTIONS, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, ABSTRACTFOOTER.services.applic.uniface.holders.ABSTRACTFOOTERTypeHolder GENERATED_PARAMETER_NAME_3, ABSTRACTFOOTER_LINK.services.applic.uniface.holders.ABSTRACTFOOTER_LINKArrayHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.GETPORTALFOOTER(GENERATED_PARAMETER_NAME_1, POPTIONS, _return, GENERATED_PARAMETER_NAME_2, GENERATED_PARAMETER_NAME_3, GENERATED_PARAMETER_NAME_4);
  }
  
  public void GETPORTALINFO(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PMENUBARFILTER, java.lang.String PMENUFILTER, java.lang.String PMENUITEMFILTER, java.lang.String POPTIONS, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, ABSTRACTPORTAL_PARAM_CONFIG.services.applic.uniface.holders.ABSTRACTPORTAL_PARAM_CONFIGArrayHolder GENERATED_PARAMETER_NAME_3, ABSTRACTPORTAL_IMAGE_CONFIG.services.applic.uniface.holders.ABSTRACTPORTAL_IMAGE_CONFIGArrayHolder GENERATED_PARAMETER_NAME_4, ABSTRACTPORTAL_MESSAGE_CONFIG.services.applic.uniface.holders.ABSTRACTPORTAL_MESSAGE_CONFIGArrayHolder GENERATED_PARAMETER_NAME_5, ABSTRACTMENU_BAR.services.applic.uniface.holders.ABSTRACTMENU_BARArrayHolder GENERATED_PARAMETER_NAME_6, ABSTRACTMENU.services.applic.uniface.holders.ABSTRACTMENUArrayHolder GENERATED_PARAMETER_NAME_7, ABSTRACTMENU_ITEM.services.applic.uniface.holders.ABSTRACTMENU_ITEMArrayHolder GENERATED_PARAMETER_NAME_8, ABSTRACTFOOTER.services.applic.uniface.holders.ABSTRACTFOOTERTypeHolder GENERATED_PARAMETER_NAME_9, ABSTRACTFOOTER_LINK.services.applic.uniface.holders.ABSTRACTFOOTER_LINKArrayHolder GENERATED_PARAMETER_NAME_10) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.GETPORTALINFO(GENERATED_PARAMETER_NAME_1, PMENUBARFILTER, PMENUFILTER, PMENUITEMFILTER, POPTIONS, _return, GENERATED_PARAMETER_NAME_2, GENERATED_PARAMETER_NAME_3, GENERATED_PARAMETER_NAME_4, GENERATED_PARAMETER_NAME_5, GENERATED_PARAMETER_NAME_6, GENERATED_PARAMETER_NAME_7, GENERATED_PARAMETER_NAME_8, GENERATED_PARAMETER_NAME_9, GENERATED_PARAMETER_NAME_10);
  }
  
  public void GETPORTALMENU(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PMENUBARFILTER, java.lang.String PMENUFILTER, java.lang.String PMENUITEMFILTER, java.lang.String POPTIONS, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, ABSTRACTMENU_BAR.services.applic.uniface.holders.ABSTRACTMENU_BARArrayHolder GENERATED_PARAMETER_NAME_3, ABSTRACTMENU.services.applic.uniface.holders.ABSTRACTMENUArrayHolder GENERATED_PARAMETER_NAME_4, ABSTRACTMENU_ITEM.services.applic.uniface.holders.ABSTRACTMENU_ITEMArrayHolder GENERATED_PARAMETER_NAME_5) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.GETPORTALMENU(GENERATED_PARAMETER_NAME_1, PMENUBARFILTER, PMENUFILTER, PMENUITEMFILTER, POPTIONS, _return, GENERATED_PARAMETER_NAME_2, GENERATED_PARAMETER_NAME_3, GENERATED_PARAMETER_NAME_4, GENERATED_PARAMETER_NAME_5);
  }
  
  public void GETPORTALPAGE(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PUSERID, javax.xml.rpc.holders.StringHolder PCURRENTPAGEID, javax.xml.rpc.holders.StringHolder PCURRENTPAGETYPE, java.lang.String POPTIONS, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, ABSTRACTPORTAL_PAGE_VIEW.services.applic.uniface.holders.ABSTRACTPORTAL_PAGE_VIEWTypeHolder GENERATED_PARAMETER_NAME_3, ABSTRACTPORTAL_PAGE_PORTLET_VIEW.services.applic.uniface.holders.ABSTRACTPORTAL_PAGE_PORTLET_VIEWArrayHolder GENERATED_PARAMETER_NAME_4, ABSTRACTPAGE_NAVIGATION.services.applic.uniface.holders.ABSTRACTPAGE_NAVIGATIONArrayHolder GENERATED_PARAMETER_NAME_5, ABSTRACTPAGE_NAVIGATION.services.applic.uniface.holders.ABSTRACTPAGE_NAVIGATIONArrayHolder GENERATED_PARAMETER_NAME_6) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.GETPORTALPAGE(GENERATED_PARAMETER_NAME_1, PUSERID, PCURRENTPAGEID, PCURRENTPAGETYPE, POPTIONS, _return, GENERATED_PARAMETER_NAME_2, GENERATED_PARAMETER_NAME_3, GENERATED_PARAMETER_NAME_4, GENERATED_PARAMETER_NAME_5, GENERATED_PARAMETER_NAME_6);
  }
  
  public void GETPORTLETCONTENT(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PPORTLETID, java.lang.String PUSERID, java.lang.String POPTIONS, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, javax.xml.rpc.holders.StringHolder PCONTENT) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.GETPORTLETCONTENT(GENERATED_PARAMETER_NAME_1, PPORTLETID, PUSERID, POPTIONS, _return, GENERATED_PARAMETER_NAME_2, PCONTENT);
  }
  
  public void GETUSERIDFROMTOKEN(java.lang.String PTOKEN, javax.xml.rpc.holders.IntHolder _return, javax.xml.rpc.holders.StringHolder PUSERID, javax.xml.rpc.holders.StringHolder PTIMESTAMP) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.GETUSERIDFROMTOKEN(PTOKEN, _return, PUSERID, PTIMESTAMP);
  }
  
  public void INSERTDOMAIN(ABSTRACTPORTAL_DOMAIN.services.applic.uniface.ABSTRACTPORTAL_DOMAINType[] GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_2, javax.xml.rpc.holders.IntHolder _return, ABSTRACTPORTAL_DOMAIN.services.applic.uniface.holders.ABSTRACTPORTAL_DOMAINArrayHolder GENERATED_PARAMETER_NAME_3, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.INSERTDOMAIN(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_2, _return, GENERATED_PARAMETER_NAME_3, GENERATED_PARAMETER_NAME_4);
  }
  
  public void INSERTDOMAINMEMBERSHIP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTGROUP_MEMBERSHIP.services.applic.uniface.ABSTRACTGROUP_MEMBERSHIPType[] GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.INSERTDOMAINMEMBERSHIP(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_2);
  }
  
  public void INSERTGROUP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTGROUP.services.applic.uniface.ABSTRACTGROUPType[] GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, ABSTRACTGROUP.services.applic.uniface.holders.ABSTRACTGROUPArrayHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.INSERTGROUP(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_2, GENERATED_PARAMETER_NAME_4);
  }
  
  public void INSERTGROUPPACKAGE(ABSTRACTGROUP_PACKAGE.services.applic.uniface.ABSTRACTGROUP_PACKAGEType[] GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_2, javax.xml.rpc.holders.IntHolder _return, ABSTRACTGROUP_PACKAGE.services.applic.uniface.holders.ABSTRACTGROUP_PACKAGEArrayHolder GENERATED_PARAMETER_NAME_3, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.INSERTGROUPPACKAGE(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_2, _return, GENERATED_PARAMETER_NAME_3, GENERATED_PARAMETER_NAME_4);
  }
  
  public void INSERTPACKAGEMEMBERSHIP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTGROUP_MEMBERSHIP.services.applic.uniface.ABSTRACTGROUP_MEMBERSHIPType[] GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.INSERTPACKAGEMEMBERSHIP(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_2);
  }
  
  public void INSERTPAGEMEMBERSHIP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTGROUP_MEMBERSHIP.services.applic.uniface.ABSTRACTGROUP_MEMBERSHIPType[] GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.INSERTPAGEMEMBERSHIP(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_2);
  }
  
  public void INSERTPORTALPAGE(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTPORTAL_PAGE.services.applic.uniface.ABSTRACTPORTAL_PAGEType[] GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, ABSTRACTPORTAL_PAGE.services.applic.uniface.holders.ABSTRACTPORTAL_PAGEArrayHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.INSERTPORTALPAGE(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_2, GENERATED_PARAMETER_NAME_4);
  }
  
  public void INSERTPORTALPAGEPORTLET(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTPORTAL_PAGE_PORTLET.services.applic.uniface.ABSTRACTPORTAL_PAGE_PORTLETType[] GENERATED_PARAMETER_NAME_3, java.lang.String PPAGETYPE, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.INSERTPORTALPAGEPORTLET(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_3, PPAGETYPE, _return, GENERATED_PARAMETER_NAME_2);
  }
  
  public void INSERTPORTLETCATEGORY(ABSTRACTPORTLET_CATEGORY.services.applic.uniface.ABSTRACTPORTLET_CATEGORYType[] GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_2, javax.xml.rpc.holders.IntHolder _return, ABSTRACTPORTLET_CATEGORY.services.applic.uniface.holders.ABSTRACTPORTLET_CATEGORYArrayHolder GENERATED_PARAMETER_NAME_3, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.INSERTPORTLETCATEGORY(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_2, _return, GENERATED_PARAMETER_NAME_3, GENERATED_PARAMETER_NAME_4);
  }
  
  public void INSERTPORTLETDOMAINMEMBERSHIP(ABSTRACTGROUP_MEMBERSHIP.services.applic.uniface.ABSTRACTGROUP_MEMBERSHIPType[] GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_2, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_3) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.INSERTPORTLETDOMAINMEMBERSHIP(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_2, _return, GENERATED_PARAMETER_NAME_3);
  }
  
  public void INSERTPORTLETMEMBERSHIP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTGROUP_MEMBERSHIP.services.applic.uniface.ABSTRACTGROUP_MEMBERSHIPType[] GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.INSERTPORTLETMEMBERSHIP(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_2);
  }
  
  public void INSERTUSERMEMBERSHIP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTPORTAL_USER_MEMBERSHIP.services.applic.uniface.ABSTRACTPORTAL_USER_MEMBERSHIPType[] GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.INSERTUSERMEMBERSHIP(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_2);
  }
  
  public void SELECTDOMAIN(ABSTRACTPORTAL_DOMAIN.services.applic.uniface.ABSTRACTPORTAL_DOMAINType GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, ABSTRACTPORTAL_DOMAIN.services.applic.uniface.holders.ABSTRACTPORTAL_DOMAINArrayHolder GENERATED_PARAMETER_NAME_2, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.SELECTDOMAIN(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_2, GENERATED_PARAMETER_NAME_4);
  }
  
  public void SELECTDOMAINMEMBERSHIP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTGROUP_MEMBERSHIP.services.applic.uniface.ABSTRACTGROUP_MEMBERSHIPType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, ABSTRACTGROUP_MEMBERSHIP.services.applic.uniface.holders.ABSTRACTGROUP_MEMBERSHIPArrayHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.SELECTDOMAINMEMBERSHIP(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_2, GENERATED_PARAMETER_NAME_4);
  }
  
  public void SELECTFILTERDOMAIN(ABSTRACTPORTAL_DOMAIN.services.applic.uniface.ABSTRACTPORTAL_DOMAINType GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, ABSTRACTPORTAL_DOMAIN.services.applic.uniface.holders.ABSTRACTPORTAL_DOMAINArrayHolder GENERATED_PARAMETER_NAME_2, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.SELECTFILTERDOMAIN(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_2, GENERATED_PARAMETER_NAME_4);
  }
  
  public void SELECTFILTERGROUP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTGROUP.services.applic.uniface.ABSTRACTGROUPType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, ABSTRACTGROUP.services.applic.uniface.holders.ABSTRACTGROUPArrayHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.SELECTFILTERGROUP(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_2, GENERATED_PARAMETER_NAME_4);
  }
  
  public void SELECTFILTERGROUPPACKAGE(ABSTRACTGROUP_PACKAGE.services.applic.uniface.ABSTRACTGROUP_PACKAGEType GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, ABSTRACTGROUP_PACKAGE.services.applic.uniface.holders.ABSTRACTGROUP_PACKAGEArrayHolder GENERATED_PARAMETER_NAME_2, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.SELECTFILTERGROUPPACKAGE(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_2, GENERATED_PARAMETER_NAME_4);
  }
  
  public void SELECTFILTERPACKAGEMEMBERSHIP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTGROUP_MEMBERSHIP.services.applic.uniface.ABSTRACTGROUP_MEMBERSHIPType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, ABSTRACTGROUP_MEMBERSHIP.services.applic.uniface.holders.ABSTRACTGROUP_MEMBERSHIPArrayHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.SELECTFILTERPACKAGEMEMBERSHIP(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_2, GENERATED_PARAMETER_NAME_4);
  }
  
  public void SELECTFILTERPORTALPAGE(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTPORTAL_PAGE.services.applic.uniface.ABSTRACTPORTAL_PAGEType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, ABSTRACTPORTAL_PAGE.services.applic.uniface.holders.ABSTRACTPORTAL_PAGEArrayHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.SELECTFILTERPORTALPAGE(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_2, GENERATED_PARAMETER_NAME_4);
  }
  
  public void SELECTFILTERPORTALPORTLET(ABSTRACTPORTLET.services.applic.uniface.ABSTRACTPORTLETType GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, ABSTRACTPORTLET.services.applic.uniface.holders.ABSTRACTPORTLETArrayHolder GENERATED_PARAMETER_NAME_2, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.SELECTFILTERPORTALPORTLET(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_2, GENERATED_PARAMETER_NAME_4);
  }
  
  public void SELECTFILTERPORTLET(ABSTRACTPORTLET.services.applic.uniface.ABSTRACTPORTLETType GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, ABSTRACTPORTLET.services.applic.uniface.holders.ABSTRACTPORTLETArrayHolder GENERATED_PARAMETER_NAME_2, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.SELECTFILTERPORTLET(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_2, GENERATED_PARAMETER_NAME_4);
  }
  
  public void SELECTFILTERPORTLETBYUSER(ABSTRACTPORTLET.services.applic.uniface.ABSTRACTPORTLETType GENERATED_PARAMETER_NAME_2, java.lang.String PUSERID, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_4, javax.xml.rpc.holders.IntHolder _return, ABSTRACTPORTLET.services.applic.uniface.holders.ABSTRACTPORTLETArrayHolder GENERATED_PARAMETER_NAME_3, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_5) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.SELECTFILTERPORTLETBYUSER(GENERATED_PARAMETER_NAME_2, PUSERID, GENERATED_PARAMETER_NAME_4, _return, GENERATED_PARAMETER_NAME_3, GENERATED_PARAMETER_NAME_5);
  }
  
  public void SELECTFILTERPORTLETCATEGORY(ABSTRACTPORTLET_CATEGORY.services.applic.uniface.ABSTRACTPORTLET_CATEGORYType GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, ABSTRACTPORTLET_CATEGORY.services.applic.uniface.holders.ABSTRACTPORTLET_CATEGORYArrayHolder GENERATED_PARAMETER_NAME_2, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.SELECTFILTERPORTLETCATEGORY(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_2, GENERATED_PARAMETER_NAME_4);
  }
  
  public void SELECTFILTERUSER(ABSTRACTPORTAL_USER.services.applic.uniface.ABSTRACTPORTAL_USERType GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, ABSTRACTPORTAL_USER.services.applic.uniface.holders.ABSTRACTPORTAL_USERArrayHolder GENERATED_PARAMETER_NAME_2, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.SELECTFILTERUSER(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_2, GENERATED_PARAMETER_NAME_4);
  }
  
  public void SELECTGROUP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTGROUP.services.applic.uniface.ABSTRACTGROUPType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, ABSTRACTGROUP.services.applic.uniface.holders.ABSTRACTGROUPArrayHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.SELECTGROUP(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_2, GENERATED_PARAMETER_NAME_4);
  }
  
  public void SELECTGROUPPACKAGE(ABSTRACTGROUP_PACKAGE.services.applic.uniface.ABSTRACTGROUP_PACKAGEType GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, ABSTRACTGROUP_PACKAGE.services.applic.uniface.holders.ABSTRACTGROUP_PACKAGEArrayHolder GENERATED_PARAMETER_NAME_2, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.SELECTGROUPPACKAGE(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_2, GENERATED_PARAMETER_NAME_4);
  }
  
  public void SELECTHTMLPORTLETCONTENT(java.lang.String PUSERID, java.lang.String PPORTLETID, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, ABSTRACTHTML_PORTLET_PROPERTY.services.applic.uniface.holders.ABSTRACTHTML_PORTLET_PROPERTYTypeHolder GENERATED_PARAMETER_NAME_4, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_5) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.SELECTHTMLPORTLETCONTENT(PUSERID, PPORTLETID, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_4, GENERATED_PARAMETER_NAME_5);
  }
  
  public void SELECTJOBDETAIL(ABSTRACTJOB_DETAIL.services.applic.uniface.ABSTRACTJOB_DETAILType GENERATED_PARAMETER_NAME_1, javax.xml.rpc.holders.IntHolder _return, ABSTRACTJOB_DETAIL.services.applic.uniface.holders.ABSTRACTJOB_DETAILArrayHolder GENERATED_PARAMETER_NAME_2, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_3) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.SELECTJOBDETAIL(GENERATED_PARAMETER_NAME_1, _return, GENERATED_PARAMETER_NAME_2, GENERATED_PARAMETER_NAME_3);
  }
  
  public void SELECTJOBTRIGGER(ABSTRACTJOB_TRIGGER.services.applic.uniface.ABSTRACTJOB_TRIGGERType GENERATED_PARAMETER_NAME_1, javax.xml.rpc.holders.IntHolder _return, ABSTRACTJOB_TRIGGER.services.applic.uniface.holders.ABSTRACTJOB_TRIGGERArrayHolder GENERATED_PARAMETER_NAME_2, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_3) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.SELECTJOBTRIGGER(GENERATED_PARAMETER_NAME_1, _return, GENERATED_PARAMETER_NAME_2, GENERATED_PARAMETER_NAME_3);
  }
  
  public void SELECTPACKAGEMEMBERSHIP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTGROUP_MEMBERSHIP.services.applic.uniface.ABSTRACTGROUP_MEMBERSHIPType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, ABSTRACTGROUP_MEMBERSHIP.services.applic.uniface.holders.ABSTRACTGROUP_MEMBERSHIPArrayHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.SELECTPACKAGEMEMBERSHIP(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_2, GENERATED_PARAMETER_NAME_4);
  }
  
  public void SELECTPAGEMEMBERSHIP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTGROUP_MEMBERSHIP.services.applic.uniface.ABSTRACTGROUP_MEMBERSHIPType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, ABSTRACTGROUP_MEMBERSHIP.services.applic.uniface.holders.ABSTRACTGROUP_MEMBERSHIPArrayHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.SELECTPAGEMEMBERSHIP(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_2, GENERATED_PARAMETER_NAME_4);
  }
  
  public void SELECTPORTALPAGE(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTPORTAL_PAGE.services.applic.uniface.ABSTRACTPORTAL_PAGEType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, ABSTRACTPORTAL_PAGE.services.applic.uniface.holders.ABSTRACTPORTAL_PAGEArrayHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.SELECTPORTALPAGE(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_2, GENERATED_PARAMETER_NAME_4);
  }
  
  public void SELECTPORTALPAGEPORTLET(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTPORTAL_PAGE_PORTLET.services.applic.uniface.ABSTRACTPORTAL_PAGE_PORTLETType GENERATED_PARAMETER_NAME_3, java.lang.String PPAGETYPE, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, ABSTRACTPORTAL_PAGE_PORTLET.services.applic.uniface.holders.ABSTRACTPORTAL_PAGE_PORTLETArrayHolder GENERATED_PARAMETER_NAME_5) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.SELECTPORTALPAGEPORTLET(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_3, PPAGETYPE, _return, GENERATED_PARAMETER_NAME_2, GENERATED_PARAMETER_NAME_5);
  }
  
  public void SELECTPORTALPORTLET(ABSTRACTPORTLET.services.applic.uniface.ABSTRACTPORTLETType GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, ABSTRACTPORTLET.services.applic.uniface.holders.ABSTRACTPORTLETArrayHolder GENERATED_PARAMETER_NAME_2, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.SELECTPORTALPORTLET(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_2, GENERATED_PARAMETER_NAME_4);
  }
  
  public void SELECTPORTLET(ABSTRACTPORTLET.services.applic.uniface.ABSTRACTPORTLETType GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, ABSTRACTPORTLET.services.applic.uniface.holders.ABSTRACTPORTLETArrayHolder GENERATED_PARAMETER_NAME_2, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.SELECTPORTLET(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_2, GENERATED_PARAMETER_NAME_4);
  }
  
  public void SELECTPORTLETCATEGORY(ABSTRACTPORTLET_CATEGORY.services.applic.uniface.ABSTRACTPORTLET_CATEGORYType GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, ABSTRACTPORTLET_CATEGORY.services.applic.uniface.holders.ABSTRACTPORTLET_CATEGORYArrayHolder GENERATED_PARAMETER_NAME_2, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.SELECTPORTLETCATEGORY(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_2, GENERATED_PARAMETER_NAME_4);
  }
  
  public void SELECTPORTLETDOMAINMEMBERSHIP(ABSTRACTGROUP_MEMBERSHIP.services.applic.uniface.ABSTRACTGROUP_MEMBERSHIPType GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, ABSTRACTGROUP_MEMBERSHIP.services.applic.uniface.holders.ABSTRACTGROUP_MEMBERSHIPArrayHolder GENERATED_PARAMETER_NAME_2, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.SELECTPORTLETDOMAINMEMBERSHIP(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_2, GENERATED_PARAMETER_NAME_4);
  }
  
  public void SELECTPORTLETMEMBERSHIP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTGROUP_MEMBERSHIP.services.applic.uniface.ABSTRACTGROUP_MEMBERSHIPType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, ABSTRACTGROUP_MEMBERSHIP.services.applic.uniface.holders.ABSTRACTGROUP_MEMBERSHIPArrayHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.SELECTPORTLETMEMBERSHIP(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_2, GENERATED_PARAMETER_NAME_4);
  }
  
  public void SELECTTEXTPORTLETCONTENT(java.lang.String PUSERID, java.lang.String PPORTLETID, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, ABSTRACTHTML_PORTLET_PROPERTY.services.applic.uniface.holders.ABSTRACTHTML_PORTLET_PROPERTYTypeHolder GENERATED_PARAMETER_NAME_4, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_5) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.SELECTTEXTPORTLETCONTENT(PUSERID, PPORTLETID, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_4, GENERATED_PARAMETER_NAME_5);
  }
  
  public void SELECTUSER(ABSTRACTPORTAL_USER.services.applic.uniface.ABSTRACTPORTAL_USERType GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, ABSTRACTPORTAL_USER.services.applic.uniface.holders.ABSTRACTPORTAL_USERArrayHolder GENERATED_PARAMETER_NAME_2, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.SELECTUSER(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_2, GENERATED_PARAMETER_NAME_4);
  }
  
  public void SELECTUSERMEMBERSHIP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTPORTAL_USER_MEMBERSHIP.services.applic.uniface.ABSTRACTPORTAL_USER_MEMBERSHIPType GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, ABSTRACTPORTAL_USER_MEMBERSHIP.services.applic.uniface.holders.ABSTRACTPORTAL_USER_MEMBERSHIPArrayHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.SELECTUSERMEMBERSHIP(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_2, GENERATED_PARAMETER_NAME_4);
  }
  
  public void UPDATEDOMAIN(ABSTRACTPORTAL_DOMAIN.services.applic.uniface.ABSTRACTPORTAL_DOMAINType[] GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_2, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_3) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.UPDATEDOMAIN(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_2, _return, GENERATED_PARAMETER_NAME_3);
  }
  
  public void UPDATEGROUP(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTGROUP.services.applic.uniface.ABSTRACTGROUPType[] GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.UPDATEGROUP(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_2);
  }
  
  public void UPDATEGROUPPACKAGE(ABSTRACTGROUP_PACKAGE.services.applic.uniface.ABSTRACTGROUP_PACKAGEType[] GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_2, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_3) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.UPDATEGROUPPACKAGE(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_2, _return, GENERATED_PARAMETER_NAME_3);
  }
  
  public void UPDATEHTMLPORTLETCONTENT(java.lang.String PUSERID, java.lang.String PPORTLETID, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, ABSTRACTHTML_PORTLET_PROPERTY.services.applic.uniface.ABSTRACTHTML_PORTLET_PROPERTYType GENERATED_PARAMETER_NAME_4, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_5) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.UPDATEHTMLPORTLETCONTENT(PUSERID, PPORTLETID, GENERATED_PARAMETER_NAME_3, GENERATED_PARAMETER_NAME_4, _return, GENERATED_PARAMETER_NAME_5);
  }
  
  public void UPDATEPORTALPAGE(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, ABSTRACTPORTAL_PAGE.services.applic.uniface.ABSTRACTPORTAL_PAGEType[] GENERATED_PARAMETER_NAME_3, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.UPDATEPORTALPAGE(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_3, _return, GENERATED_PARAMETER_NAME_2);
  }
  
  public void UPDATEPORTLET(ABSTRACTPORTLET.services.applic.uniface.ABSTRACTPORTLETType[] GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_2, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_3) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.UPDATEPORTLET(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_2, _return, GENERATED_PARAMETER_NAME_3);
  }
  
  public void UPDATEPORTLETCATEGORY(ABSTRACTPORTLET_CATEGORY.services.applic.uniface.ABSTRACTPORTLET_CATEGORYType[] GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_2, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_3) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.UPDATEPORTLETCATEGORY(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_2, _return, GENERATED_PARAMETER_NAME_3);
  }
  
  public void UPDATETEXTPORTLETCONTENT(java.lang.String PUSERID, java.lang.String PPORTLETID, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_3, ABSTRACTHTML_PORTLET_PROPERTY.services.applic.uniface.ABSTRACTHTML_PORTLET_PROPERTYType GENERATED_PARAMETER_NAME_4, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_5) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.UPDATETEXTPORTLETCONTENT(PUSERID, PPORTLETID, GENERATED_PARAMETER_NAME_3, GENERATED_PARAMETER_NAME_4, _return, GENERATED_PARAMETER_NAME_5);
  }
  
  public void UPDATEUSER(ABSTRACTPORTAL_USER.services.applic.uniface.ABSTRACTPORTAL_USERType[] GENERATED_PARAMETER_NAME_1, STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_2, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_3) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.UPDATEUSER(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_2, _return, GENERATED_PARAMETER_NAME_3);
  }
  
  public void UPDATEUSERPASSWORD(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, java.lang.String PUSERID, java.lang.String PPASSWORD, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.UPDATEUSERPASSWORD(GENERATED_PARAMETER_NAME_1, PUSERID, PPASSWORD, _return, GENERATED_PARAMETER_NAME_4);
  }
  
  public void VALIDATEPORTALUSER(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, STANDARDCOOKIE_CONTEXT.services.applic.uniface.STANDARDCOOKIE_CONTEXTType GENERATED_PARAMETER_NAME_2, javax.xml.rpc.holders.IntHolder _return, javax.xml.rpc.holders.StringHolder PUSERID, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_4, STANDARDCOOKIE_CONTEXT.services.applic.uniface.holders.STANDARDCOOKIE_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_5, javax.xml.rpc.holders.BooleanHolder PISVALIDATED) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.VALIDATEPORTALUSER(GENERATED_PARAMETER_NAME_1, GENERATED_PARAMETER_NAME_2, _return, PUSERID, GENERATED_PARAMETER_NAME_4, GENERATED_PARAMETER_NAME_5, PISVALIDATED);
  }
  
  public void VALIDATEUSER(STANDARDSECURITY_CONTEXT.services.applic.uniface.STANDARDSECURITY_CONTEXTType GENERATED_PARAMETER_NAME_1, javax.xml.rpc.holders.IntHolder _return, STANDARDSTATUS_CONTEXT.services.applic.uniface.holders.STANDARDSTATUS_CONTEXTTypeHolder GENERATED_PARAMETER_NAME_2, javax.xml.rpc.holders.BooleanHolder PISVALIDATED) throws java.rmi.RemoteException{
    if (uVCONNECTORPortType == null)
      _initUVCONNECTORPortTypeProxy();
    uVCONNECTORPortType.VALIDATEUSER(GENERATED_PARAMETER_NAME_1, _return, GENERATED_PARAMETER_NAME_2, PISVALIDATED);
  }
  
  
}