package com.compuware.caqs.CStyle.AST;
/* Generated By:JJTree: Do not edit this line. ASTdeclaration_specifiers.java */

public class ASTdeclaration_specifiers extends SimpleNode {
  public ASTdeclaration_specifiers(int id) {
    super(id);
  }

  public ASTdeclaration_specifiers(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
