package com.compuware.caqs.CStyle.AST;
/* Generated By:JJTree: Do not edit this line. ASTinit_declarator_list.java */

public class ASTinit_declarator_list extends SimpleNode {
  public ASTinit_declarator_list(int id) {
    super(id);
  }

  public ASTinit_declarator_list(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
