package com.compuware.caqs.CStyle.AST;
/* Generated By:JJTree: Do not edit this line. ASTstatement_list.java */

public class ASTstatement_list extends SimpleNode {
  public ASTstatement_list(int id) {
    super(id);
  }

  public ASTstatement_list(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
