package com.compuware.caqs.CStyle.AST;
/* Generated By:JJTree: Do not edit this line. ASTscope_override.java */

public class ASTscope_override extends SimpleNode {
  public ASTscope_override(int id) {
    super(id);
  }

  public ASTscope_override(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
