/*
 * ErrorDialog.java
 *
 * Created on 9 janvier 2003, 15:54
 */

package com.compuware.caqs.presentation.applets.architecture.panels.graphpanels;

import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.Toolkit;

import com.compuware.caqs.presentation.applets.architecture.I18n;
/**
 *
 * @author  cwfr-fxalbouy
 */
public class ErrorDialog extends java.awt.Dialog {
    
    /** Creates new form ErrorDialog */
    public ErrorDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         /* Center the window */
        Dimension screenDim = Toolkit.getDefaultToolkit().getScreenSize();
        Rectangle winDim = getBounds();
        setLocation((screenDim.width - winDim.width) / 2,
		(screenDim.height - winDim.height) / 2);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {
        label1 = new java.awt.Label();
        button1 = new java.awt.Button();

        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setName(I18n.getString("error"));
        label1.setText(I18n.getString("weightError"));
        add(label1, java.awt.BorderLayout.CENTER);

        button1.setLabel(I18n.getString("ok"));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        add(button1, java.awt.BorderLayout.SOUTH);

        pack();
    }

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {
        // Add your handling code here:
        this.closeDialog(null);
    }
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {
        setVisible(false);
        dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new ErrorDialog(new java.awt.Frame(), true).setVisible(true);
    }
    
    
    // Variables declaration - do not modify
    private java.awt.Button button1;
    private java.awt.Label label1;
    // End of variables declaration
    
}
