INSERT INTO SETTINGS(SETTING_ID,SETTING_DESC,SETTING_DEFAULT) VALUES ('MESSAGE_LOCATION','Message zone location','message-location-north');
INSERT INTO SETTINGS_VALUES(SETTING_ID,SETTING_VALUE) VALUES ('MESSAGE_LOCATION','message-location-north');
INSERT INTO SETTINGS_VALUES(SETTING_ID,SETTING_VALUE) VALUES ('MESSAGE_LOCATION','message-location-south');

INSERT INTO I18N (TABLE_NAME,COLUMN_NAME,ID_TABLE,ID_LANGUE,TEXT) VALUES ('setting_value','lib','message-location-north','fr','En haut');
INSERT INTO I18N (TABLE_NAME,COLUMN_NAME,ID_TABLE,ID_LANGUE,TEXT) VALUES ('setting_value','lib','message-location-south','fr','En bas');
INSERT INTO I18N (TABLE_NAME,COLUMN_NAME,ID_TABLE,ID_LANGUE,TEXT) VALUES ('setting_value','lib','message-location-north','en','Up');
INSERT INTO I18N (TABLE_NAME,COLUMN_NAME,ID_TABLE,ID_LANGUE,TEXT) VALUES ('setting_value','lib','message-location-south','en','Down');

DROP TABLE BLOB_TABLE;
DROP TABLE FICHE_LINKS;
DROP TABLE FICHE_CONNAISSANCE;

INSERT INTO SETTINGS(SETTING_ID,SETTING_DESC,SETTING_DEFAULT) VALUES ('STARTING_PAGE','CAQS Starting page','quality');
INSERT INTO SETTINGS_VALUES(SETTING_ID,SETTING_VALUE) VALUES ('STARTING_PAGE','dashboard');
INSERT INTO SETTINGS_VALUES(SETTING_ID,SETTING_VALUE) VALUES ('STARTING_PAGE','quality');
INSERT INTO SETTINGS_VALUES(SETTING_ID,SETTING_VALUE) VALUES ('STARTING_PAGE','administration');
INSERT INTO SETTINGS_VALUES(SETTING_ID,SETTING_VALUE) VALUES ('STARTING_PAGE','architecture');
INSERT INTO SETTINGS_VALUES(SETTING_ID,SETTING_VALUE) VALUES ('STARTING_PAGE','justification');
INSERT INTO SETTINGS_VALUES(SETTING_ID,SETTING_VALUE) VALUES ('STARTING_PAGE','labellisation');

INSERT INTO I18N (TABLE_NAME,COLUMN_NAME,ID_TABLE,ID_LANGUE,TEXT) VALUES ('setting_value','lib','dashboard','fr','Tableau de bord');
INSERT INTO I18N (TABLE_NAME,COLUMN_NAME,ID_TABLE,ID_LANGUE,TEXT) VALUES ('setting_value','lib','dashboard','en','Dashboard');
INSERT INTO I18N (TABLE_NAME,COLUMN_NAME,ID_TABLE,ID_LANGUE,TEXT) VALUES ('setting_value','lib','quality','fr','Gestion qualité');
INSERT INTO I18N (TABLE_NAME,COLUMN_NAME,ID_TABLE,ID_LANGUE,TEXT) VALUES ('setting_value','lib','quality','en','Quality management');
INSERT INTO I18N (TABLE_NAME,COLUMN_NAME,ID_TABLE,ID_LANGUE,TEXT) VALUES ('setting_value','lib','administration','fr','Administration');
INSERT INTO I18N (TABLE_NAME,COLUMN_NAME,ID_TABLE,ID_LANGUE,TEXT) VALUES ('setting_value','lib','administration','en','Administration');
INSERT INTO I18N (TABLE_NAME,COLUMN_NAME,ID_TABLE,ID_LANGUE,TEXT) VALUES ('setting_value','lib','architecture','fr','Architecture');
INSERT INTO I18N (TABLE_NAME,COLUMN_NAME,ID_TABLE,ID_LANGUE,TEXT) VALUES ('setting_value','lib','architecture','en','Architecture');
INSERT INTO I18N (TABLE_NAME,COLUMN_NAME,ID_TABLE,ID_LANGUE,TEXT) VALUES ('setting_value','lib','justification','fr','Justification');
INSERT INTO I18N (TABLE_NAME,COLUMN_NAME,ID_TABLE,ID_LANGUE,TEXT) VALUES ('setting_value','lib','justification','en','Justification');
INSERT INTO I18N (TABLE_NAME,COLUMN_NAME,ID_TABLE,ID_LANGUE,TEXT) VALUES ('setting_value','lib','labellisation','fr','Labellisation');
INSERT INTO I18N (TABLE_NAME,COLUMN_NAME,ID_TABLE,ID_LANGUE,TEXT) VALUES ('setting_value','lib','labellisation','en','Labelling');

delete from i18n where table_name = 'unifaceview';

INSERT INTO SETTINGS_VALUES(SETTING_ID,SETTING_VALUE) VALUES ('COLOR_THEME','theme-light-brown');
INSERT INTO I18N (TABLE_NAME,COLUMN_NAME,ID_TABLE,ID_LANGUE,TEXT) VALUES ('setting_value','lib','theme-light-brown','fr','Marron clair');
INSERT INTO I18N (TABLE_NAME,COLUMN_NAME,ID_TABLE,ID_LANGUE,TEXT) VALUES ('setting_value','lib','theme-light-brown','en','Light brown');
INSERT INTO SETTINGS_VALUES(SETTING_ID,SETTING_VALUE) VALUES ('COLOR_THEME','theme-light-green');
INSERT INTO I18N (TABLE_NAME,COLUMN_NAME,ID_TABLE,ID_LANGUE,TEXT) VALUES ('setting_value','lib','theme-light-green','fr','Vert clair');
INSERT INTO I18N (TABLE_NAME,COLUMN_NAME,ID_TABLE,ID_LANGUE,TEXT) VALUES ('setting_value','lib','theme-light-green','en','Light green');
INSERT INTO SETTINGS_VALUES(SETTING_ID,SETTING_VALUE) VALUES ('COLOR_THEME','theme-light-orange');
INSERT INTO I18N (TABLE_NAME,COLUMN_NAME,ID_TABLE,ID_LANGUE,TEXT) VALUES ('setting_value','lib','theme-light-orange','fr','Orange clair');
INSERT INTO I18N (TABLE_NAME,COLUMN_NAME,ID_TABLE,ID_LANGUE,TEXT) VALUES ('setting_value','lib','theme-light-orange','en','Light orange');
INSERT INTO SETTINGS_VALUES(SETTING_ID,SETTING_VALUE) VALUES ('COLOR_THEME','theme-light-wine');
INSERT INTO I18N (TABLE_NAME,COLUMN_NAME,ID_TABLE,ID_LANGUE,TEXT) VALUES ('setting_value','lib','theme-light-wine','fr','Vin clair');
INSERT INTO I18N (TABLE_NAME,COLUMN_NAME,ID_TABLE,ID_LANGUE,TEXT) VALUES ('setting_value','lib','theme-light-wine','en','Light wine');

INSERT INTO SETTINGS(SETTING_ID,SETTING_DESC,SETTING_DEFAULT) VALUES ('LAST_ANALYSIS_DATE_WARNING','Maximum number of days since last analysis before being warned','21');

INSERT INTO CAQS_TASKS (ID_TASK,TYPE_TASK,SHOW_USER) VALUES ('DATA_UPLOAD','INFO','NEVER');

INSERT INTO CAQS_ACCESS_DEFINITION (ID_ACCESS, LIB_ACCESS) VALUES ('ADMINISTRATION_ACCESS', 'Access administration');
INSERT INTO CAQS_ACCESS_RIGHTS (ID_ACCESS, ID_ROLE) VALUES ('ADMINISTRATION_ACCESS', 'PROJECTMANAGER');
INSERT INTO CAQS_ACCESS_RIGHTS (ID_ACCESS, ID_ROLE) VALUES ('ADMINISTRATION_ACCESS', 'ADMINISTRATOR');
INSERT INTO CAQS_ACCESS_RIGHTS (ID_ACCESS, ID_ROLE) VALUES ('ADMINISTRATION_ACCESS', 'QUALITYEXPERT');

CREATE TABLE STATS (
   PERIOD  date NOT NULL,
   SUMCONN number(12) NOT NULL,
   MAXCONN number(12) NOT NULL
)
STORAGE (
 	INITIAL 	64 K
	NEXT 	  	64 K
	PCTINCREASE 10 
)
TABLESPACE %TABLE_TBS%;

ALTER TABLE STATS
 ADD CONSTRAINT STATSP1
  PRIMARY KEY (PERIOD) 
  USING INDEX 
   STORAGE (INITIAL 64K NEXT 64K PCTINCREASE 0) TABLESPACE %INDEX_TBS%
; 

-- 2009-04-30 daz
INSERT INTO CAQS_ACCESS_DEFINITION (ID_ACCESS, LIB_ACCESS) VALUES ('DASHBOARD_CONNECTION_TIMELINE', 'Right to see the connection graph in the timeplot');
INSERT INTO CAQS_ACCESS_RIGHTS (ID_ACCESS, ID_ROLE) VALUES ('DASHBOARD_CONNECTION_TIMELINE', 'ADMINISTRATOR');
INSERT INTO SETTINGS(SETTING_ID,SETTING_DESC,SETTING_DEFAULT) VALUES ('DISPLAY_GLOBAL_BASELINES_TIMEPLOT','Display the global baselines timeplot on dashboard','true');
INSERT INTO SETTINGS(SETTING_ID,SETTING_DESC,SETTING_DEFAULT) VALUES ('DISPLAY_CONNECTIONS_TIMEPLOT','Display the connections timeplot on dashboard','true');

-- 25/08/2009 11:31:02 lai
-- change user ids to lowercase to be compatible with new exo user management
update droits set ID_PROFIL_USER=lower(id_profil_user);
