ALTER TABLE ARCHI_LINK MODIFY(ID_PROJ VARCHAR2(64));
ALTER TABLE LINK_REAL MODIFY(ID_PROJ VARCHAR2(64));
ALTER TABLE PACKAGE MODIFY(ID_PROJ VARCHAR2(64));

ALTER TABLE LANGUE MODIFY(ID VARCHAR2(32));
ALTER TABLE METRIQUE MODIFY(OUTIL_MET VARCHAR2(40));

commit;
