INSERT INTO CAQS_ACCESS_DEFINITION (ID_ACCESS, LIB_ACCESS) VALUES ('ADMIN_DOMAIN_MODIFICATION', 'Possibility to modify domains information');
INSERT INTO CAQS_ACCESS_RIGHTS (ID_ACCESS, ID_ROLE) VALUES ('ADMIN_DOMAIN_MODIFICATION', 'ADMINISTRATOR');
