ALTER TABLE BASELINE DROP COLUMN INFOS_BLINE;
ALTER TABLE BLOB_TABLE DROP COLUMN BLOB_DATA;
ALTER TABLE CATEGORIE DROP COLUMN INFOS_CAT;
ALTER TABLE CRITERE DROP COLUMN INFOS_CRIT;
ALTER TABLE ELEMENT DROP COLUMN DTD_ELT;
ALTER TABLE ELEMENT DROP COLUMN XML_ELT;
ALTER TABLE ELEMENT DROP COLUMN INFOS_ELT;
ALTER TABLE FACTEUR DROP COLUMN INFOS_FACT;
ALTER TABLE JUSTIFICATION DROP COLUMN INFOS_JUST;
ALTER TABLE LABELLISATION DROP COLUMN INFOS_LABEL;
ALTER TABLE METRIQUE DROP COLUMN INFOS_MET;
ALTER TABLE NIVEAU DROP COLUMN INFOS_NIV;
ALTER TABLE PACKAGE DROP COLUMN INFOS_PACK;
ALTER TABLE POIDS_FACT_CRIT DROP COLUMN INFOS_POIDS;
ALTER TABLE PROJET DROP COLUMN INFOS_PRO;
ALTER TABLE REGLE DROP COLUMN INFOS_REG;
ALTER TABLE TYPE_ELEMENT DROP COLUMN INFOS_TELT;
ALTER TABLE TYPE_LABELLISATION DROP COLUMN INFOS_TYPLAB;
ALTER TABLE TYPE_METRIQUE DROP COLUMN INFOS_TMET;
ALTER TABLE USAGE DROP COLUMN INFOS_USA;

commit;

ALTER TABLE QAMETRIQUE RENAME COLUMN LINES TO LIGNES;

ALTER TABLE PROJET DROP CONSTRAINT USAGE_PROJET;
ALTER TABLE PROJET DROP COLUMN USA_PRO;

CREATE TABLE MODELE ( 
  ID_USA            VARCHAR2 (32)  NOT NULL, 
  LIB_USA           VARCHAR2 (32), 
  DESC_USA          VARCHAR2 (128), 
  DINTS_USA         DATE, 
  DMAJ_USA          DATE, 
  DAPPLICATION_USA  DATE, 
  DPEREMPTION_USA   DATE)
   TABLESPACE %TABLE_TBS%
;

ALTER TABLE MODELE
 ADD CONSTRAINT MODELEP1
  PRIMARY KEY (ID_USA) 
  USING INDEX 
  TABLESPACE %INDEX_TBS% 
; 

INSERT INTO MODELE SELECT * FROM USAGE;
commit;

DROP TABLE USAGE CASCADE CONSTRAINTS;

ALTER TABLE CRITERE_USAGE ADD CONSTRAINT CRITERE_USAGE_USAGE
 FOREIGN KEY (ID_USA) 
  REFERENCES MODELE (ID_USA) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ELEMENT ADD  CONSTRAINT MODELE_ELEMENT
 FOREIGN KEY (ID_USA) 
  REFERENCES MODELE (ID_USA) ;

CREATE INDEX ELEMENT_BASELINE_INFO ON 
  ELEMENT_BASELINE_INFO(ID_BLINE, ID_MAIN_ELT) 
  TABLESPACE %INDEX_TBS% 
; 

