alter table METRIQUE modify DESC_MET VARCHAR2(768);

ALTER TABLE Element ADD filePath VARCHAR2(2048);
ALTER TABLE Element ADD linePos INTEGER;
commit;

INSERT INTO METRIQUE ( ID_MET, LIB_MET, DESC_MET, OUTIL_MET ) VALUES ('R0001', 'R0001', 'Class overrides equals() without overriding hashCode()', 'DEVPARTNER');
INSERT INTO METRIQUE ( ID_MET, LIB_MET, DESC_MET, OUTIL_MET ) VALUES ('R0002', 'R0002', 'equals() is overloaded without overriding it', 'DEVPARTNER'); 
INSERT INTO METRIQUE ( ID_MET, LIB_MET, DESC_MET, OUTIL_MET ) VALUES ('R0003', 'R0003', 'Public class exposes a public field', 'DEVPARTNER'); 
INSERT INTO METRIQUE ( ID_MET, LIB_MET, DESC_MET, OUTIL_MET ) VALUES ('R0004', 'R0004', 'Java name conventions not followed', 'DEVPARTNER'); 
INSERT INTO METRIQUE ( ID_MET, LIB_MET, DESC_MET, OUTIL_MET ) VALUES ('R0005', 'R0005', 'Public static final field contains a mutable object', 'DEVPARTNER'); 
INSERT INTO METRIQUE ( ID_MET, LIB_MET, DESC_MET, OUTIL_MET ) VALUES ('R0006', 'R0006', 'Loop terminated by an exception', 'DEVPARTNER'); 
INSERT INTO METRIQUE ( ID_MET, LIB_MET, DESC_MET, OUTIL_MET ) VALUES ('R0007', 'R0007', 'Overridable method is invoked in constructor, clone() or readObject()', 'DEVPARTNER'); 
INSERT INTO METRIQUE ( ID_MET, LIB_MET, DESC_MET, OUTIL_MET ) VALUES ('R0008', 'R0008', 'Abstract class does not implement an interface', 'DEVPARTNER'); 
INSERT INTO METRIQUE ( ID_MET, LIB_MET, DESC_MET, OUTIL_MET ) VALUES ('R0009', 'R0009', 'Interface used to only define constants', 'DEVPARTNER'); 
INSERT INTO METRIQUE ( ID_MET, LIB_MET, DESC_MET, OUTIL_MET ) VALUES ('R0010', 'R0010', 'Public method does not check for null parameter', 'DEVPARTNER'); 
INSERT INTO METRIQUE ( ID_MET, LIB_MET, DESC_MET, OUTIL_MET ) VALUES ('R0011', 'R0011', 'Parameter list longer than recommended by convention', 'DEVPARTNER'); 
INSERT INTO METRIQUE ( ID_MET, LIB_MET, DESC_MET, OUTIL_MET ) VALUES ('R0012', 'R0012', 'Class implements Cloneable without a clone() method', 'DEVPARTNER'); 
INSERT INTO METRIQUE ( ID_MET, LIB_MET, DESC_MET, OUTIL_MET ) VALUES ('R0013', 'R0013', 'Ambiguous method overloading', 'DEVPARTNER'); 
INSERT INTO METRIQUE ( ID_MET, LIB_MET, DESC_MET, OUTIL_MET ) VALUES ('R0014', 'R0014', 'Method returns null instead of a zero-length array', 'DEVPARTNER'); 
INSERT INTO METRIQUE ( ID_MET, LIB_MET, DESC_MET, OUTIL_MET ) VALUES ('R0015', 'R0015', 'Caught exception is ignored', 'DEVPARTNER'); 
INSERT INTO METRIQUE ( ID_MET, LIB_MET, DESC_MET, OUTIL_MET ) VALUES ('R0016', 'R0016', 'Class extends java.lang.Error instead of RuntimeException', 'DEVPARTNER'); 
INSERT INTO METRIQUE ( ID_MET, LIB_MET, DESC_MET, OUTIL_MET ) VALUES ('R0017', 'R0017', 'Overridable method invoked in synchronized block', 'DEVPARTNER'); 
INSERT INTO METRIQUE ( ID_MET, LIB_MET, DESC_MET, OUTIL_MET ) VALUES ('R0018', 'R0018', 'wait() invoked without using a wait loop', 'DEVPARTNER'); 
INSERT INTO METRIQUE ( ID_MET, LIB_MET, DESC_MET, OUTIL_MET ) VALUES ('R0019', 'R0019', 'Inner class implements Serializable', 'DEVPARTNER'); 
INSERT INTO METRIQUE ( ID_MET, LIB_MET, DESC_MET, OUTIL_MET ) VALUES ('R0020', 'R0020', 'Serializable class does not include a serialVersionUID field', 'DEVPARTNER'); 
INSERT INTO METRIQUE ( ID_MET, LIB_MET, DESC_MET, OUTIL_MET ) VALUES ('R0021', 'R0021', 'finalize() does not call super.finalize()', 'DEVPARTNER'); 
INSERT INTO METRIQUE ( ID_MET, LIB_MET, DESC_MET, OUTIL_MET ) VALUES ('R0022', 'R0022', 'toString() not overridden in public class', 'DEVPARTNER'); 
INSERT INTO METRIQUE ( ID_MET, LIB_MET, DESC_MET, OUTIL_MET ) VALUES ('R0023', 'R0023', 'equals() does not use instanceof to check parameter type', 'DEVPARTNER'); 
INSERT INTO METRIQUE ( ID_MET, LIB_MET, DESC_MET, OUTIL_MET ) VALUES ('R0024', 'R0024', 'equals() does not check for equality with this', 'DEVPARTNER'); 
INSERT INTO METRIQUE ( ID_MET, LIB_MET, DESC_MET, OUTIL_MET ) VALUES ('R0025', 'R0025', 'clone() does not call super.clone()', 'DEVPARTNER'); 
INSERT INTO METRIQUE ( ID_MET, LIB_MET, DESC_MET, OUTIL_MET ) VALUES ('R0026', 'R0026', 'readResolve() or writeReplace() declared private in Serializable class', 'DEVPARTNER'); 
INSERT INTO METRIQUE ( ID_MET, LIB_MET, DESC_MET, OUTIL_MET ) VALUES ('R0027', 'R0027', 'Serializable Singleton class needs readResolve() method', 'DEVPARTNER'); 
INSERT INTO METRIQUE ( ID_MET, LIB_MET, DESC_MET, OUTIL_MET ) VALUES ( 'R0028', 'R0028', 'JDBC object does not call its close() method', 'DEVPARTNER'); 
INSERT INTO METRIQUE ( ID_MET, LIB_MET, DESC_MET, OUTIL_MET ) VALUES ( 'R0030'  ,'R0030'  , 'Class overrides equals() without implementing Comparable', 'DEVPARTNER');

commit;

update qametrique set id_met='R0001' where id_met='R1';
update qametrique set id_met='R0002' where id_met='R2';
update qametrique set id_met='R0003' where id_met='R3';
update qametrique set id_met='R0004' where id_met='R4';
update qametrique set id_met='R0005' where id_met='R5';
update qametrique set id_met='R0006' where id_met='R6';
update qametrique set id_met='R0007' where id_met='R7';
update qametrique set id_met='R0008' where id_met='R8';
update qametrique set id_met='R0009' where id_met='R9';
update qametrique set id_met='R0010' where id_met='R10';
update qametrique set id_met='R0011' where id_met='R11';
update qametrique set id_met='R0012' where id_met='R12';
update qametrique set id_met='R0013' where id_met='R13';
update qametrique set id_met='R0014' where id_met='R14';
update qametrique set id_met='R0015' where id_met='R15';
update qametrique set id_met='R0016' where id_met='R16';
update qametrique set id_met='R0017' where id_met='R17';
update qametrique set id_met='R0018' where id_met='R18';
update qametrique set id_met='R0019' where id_met='R19';
update qametrique set id_met='R0020' where id_met='R20';
update qametrique set id_met='R0021' where id_met='R21';
update qametrique set id_met='R0022' where id_met='R22';
update qametrique set id_met='R0023' where id_met='R23';
update qametrique set id_met='R0024' where id_met='R24';
update qametrique set id_met='R0025' where id_met='R25';
update qametrique set id_met='R0026' where id_met='R26';
update qametrique set id_met='R0027' where id_met='R27';
update qametrique set id_met='R0028' where id_met='R28';
update qametrique set id_met='R0030' where id_met='R30';

commit;

update regle set id_met='R0001' where id_met='R1';
update regle set id_met='R0002' where id_met='R2';
update regle set id_met='R0003' where id_met='R3';
update regle set id_met='R0004' where id_met='R4';
update regle set id_met='R0005' where id_met='R5';
update regle set id_met='R0006' where id_met='R6';
update regle set id_met='R0007' where id_met='R7';
update regle set id_met='R0008' where id_met='R8';
update regle set id_met='R0009' where id_met='R9';
update regle set id_met='R0010' where id_met='R10';
update regle set id_met='R0011' where id_met='R11';
update regle set id_met='R0012' where id_met='R12';
update regle set id_met='R0013' where id_met='R13';
update regle set id_met='R0014' where id_met='R14';
update regle set id_met='R0015' where id_met='R15';
update regle set id_met='R0016' where id_met='R16';
update regle set id_met='R0017' where id_met='R17';
update regle set id_met='R0018' where id_met='R18';
update regle set id_met='R0019' where id_met='R19';
update regle set id_met='R0020' where id_met='R20';
update regle set id_met='R0021' where id_met='R21';
update regle set id_met='R0022' where id_met='R22';
update regle set id_met='R0023' where id_met='R23';
update regle set id_met='R0024' where id_met='R24';
update regle set id_met='R0025' where id_met='R25';
update regle set id_met='R0026' where id_met='R26';
update regle set id_met='R0027' where id_met='R27';
update regle set id_met='R0028' where id_met='R28';
update regle set id_met='R0030' where id_met='R30';

commit;

update seuil set id_met='R0001' where id_met='R1';
update seuil set id_met='R0002' where id_met='R2';
update seuil set id_met='R0003' where id_met='R3';
update seuil set id_met='R0004' where id_met='R4';
update seuil set id_met='R0005' where id_met='R5';
update seuil set id_met='R0006' where id_met='R6';
update seuil set id_met='R0007' where id_met='R7';
update seuil set id_met='R0008' where id_met='R8';
update seuil set id_met='R0009' where id_met='R9';
update seuil set id_met='R0010' where id_met='R10';
update seuil set id_met='R0011' where id_met='R11';
update seuil set id_met='R0012' where id_met='R12';
update seuil set id_met='R0013' where id_met='R13';
update seuil set id_met='R0014' where id_met='R14';
update seuil set id_met='R0015' where id_met='R15';
update seuil set id_met='R0016' where id_met='R16';
update seuil set id_met='R0017' where id_met='R17';
update seuil set id_met='R0018' where id_met='R18';
update seuil set id_met='R0019' where id_met='R19';
update seuil set id_met='R0020' where id_met='R20';
update seuil set id_met='R0021' where id_met='R21';
update seuil set id_met='R0022' where id_met='R22';
update seuil set id_met='R0023' where id_met='R23';
update seuil set id_met='R0024' where id_met='R24';
update seuil set id_met='R0025' where id_met='R25';
update seuil set id_met='R0026' where id_met='R26';
update seuil set id_met='R0027' where id_met='R27';
update seuil set id_met='R0028' where id_met='R28';
update seuil set id_met='R0030' where id_met='R30';

commit;

delete from metrique where id_met='R1';
delete from metrique where id_met='R2';
delete from metrique where id_met='R3';
delete from metrique where id_met='R4';
delete from metrique where id_met='R5';
delete from metrique where id_met='R6';
delete from metrique where id_met='R7';
delete from metrique where id_met='R8';
delete from metrique where id_met='R9';
delete from metrique where id_met='R10';
delete from metrique where id_met='R11';
delete from metrique where id_met='R12';
delete from metrique where id_met='R13';
delete from metrique where id_met='R14';
delete from metrique where id_met='R15';
delete from metrique where id_met='R16';
delete from metrique where id_met='R17';
delete from metrique where id_met='R18';
delete from metrique where id_met='R19';
delete from metrique where id_met='R20';
delete from metrique where id_met='R21';
delete from metrique where id_met='R22';
delete from metrique where id_met='R23';
delete from metrique where id_met='R24';
delete from metrique where id_met='R25';
delete from metrique where id_met='R26';
delete from metrique where id_met='R27';
delete from metrique where id_met='R28';
delete from metrique where id_met='R30';

commit;
