CREATE TABLE STEREOTYPE (
   ID_STEREOTYPE       VARCHAR2 (64) NOT NULL,
   LIB_STEREOTYPE      VARCHAR2 (64) NOT NULL,
   DESC_STEREOTYPE     VARCHAR2 (256) NOT NULL)
   TABLESPACE %TABLE_TBS%
;

ALTER TABLE STEREOTYPE
  ADD CONSTRAINT STEREOTYPEP1
  PRIMARY KEY (ID_STEREOTYPE) 
  USING INDEX 
  TABLESPACE %INDEX_TBS% 
;

ALTER TABLE ELEMENT ADD ID_STEREOTYPE VARCHAR2 (64) NULL;

ALTER TABLE ELEMENT ADD CONSTRAINT STEREOTYPE_ELEMENT
 FOREIGN KEY (ID_STEREOTYPE)
  REFERENCES STEREOTYPE (ID_STEREOTYPE) ;


alter table REGLE modify ID_MET VARCHAR2(64);
