CREATE USER "PQLAPP" PROFILE "DEFAULT" IDENTIFIED BY "pqlapp" 
    DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT UNLIMITED TABLESPACE TO pqlapp;
GRANT CONNECT TO pqlapp;
GRANT DBA TO pqlapp;
GRANT RESOURCE TO pqlapp;
connect pqlapp/pqlapp;
