CREATE TABLESPACE "%TABLE_TBS%" 
    DATAFILE '%ORACLEBASEDIR%\%TABLE_TBS%.ora' SIZE 512M REUSE AUTOEXTEND ON NEXT 128M MAXSIZE 1024M;
	
CREATE TABLESPACE "%INDEX_TBS%" 
    DATAFILE '%ORACLEBASEDIR%\%INDEX_TBS%.ora' SIZE 512M REUSE AUTOEXTEND ON NEXT 128M MAXSIZE 2048M;
