Alter index USAGEP1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index TYPE_METRIQUEP1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index TYPE_LABELLISATIONP1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index TYPE_FICHEP1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index TYPE_ELEMENTP1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index TECHNOLOGIEP1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index SEVERITEP1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index SEUILP1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index SEUILI3 rebuild
TABLESPACE %INDEX_TBS%;

Alter index SEUILI2 rebuild
TABLESPACE %INDEX_TBS%;

Alter index REGLEP1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index REGLEI2 rebuild
TABLESPACE %INDEX_TBS%;

Alter index QAMETRIQUEP1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index QAMETRIQUEI5 rebuild
TABLESPACE %INDEX_TBS%;

Alter index QAMETRIQUEI4 rebuild
TABLESPACE %INDEX_TBS%;

Alter index QAMETRIQUEI3 rebuild
TABLESPACE %INDEX_TBS%;

Alter index QAMETRIQUEI2 rebuild
TABLESPACE %INDEX_TBS%;

Alter index PROJETP1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index PROJETI2 rebuild
TABLESPACE %INDEX_TBS%;

Alter index PRIMARYKEY rebuild
TABLESPACE %INDEX_TBS%;

Alter index POIDS_FACT_CRITP1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index POIDS_FACT_CRITI6 rebuild
TABLESPACE %INDEX_TBS%;

Alter index POIDS_FACT_CRITI5 rebuild
TABLESPACE %INDEX_TBS%;

Alter index POIDS_FACT_CRITI4 rebuild
TABLESPACE %INDEX_TBS%;

Alter index POIDS_FACT_CRITI3 rebuild
TABLESPACE %INDEX_TBS%;

Alter index POIDS_FACT_CRITI2 rebuild
TABLESPACE %INDEX_TBS%;

Alter index POIDS_FACT_CRITI1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index PACKAGEP1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index PACKAGEI3 rebuild
TABLESPACE %INDEX_TBS%;

Alter index PACKAGEI2 rebuild
TABLESPACE %INDEX_TBS%;

Alter index OUTILSP1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index NIVEAUP1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index METRIQUEP1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index METRIQUEI5 rebuild
TABLESPACE %INDEX_TBS%;

Alter index METRIQUEI4 rebuild
TABLESPACE %INDEX_TBS%;

Alter index METRIQUEI2 rebuild
TABLESPACE %INDEX_TBS%;

Alter index LINK_REAL_PRIMARY rebuild
TABLESPACE %INDEX_TBS%;

Alter index LINK_REALI1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index LINK_ELT_BLIN_PRIMARY rebuild
TABLESPACE %INDEX_TBS%;

Alter index LINK_ELT_BLINEI1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index LANGAGEP1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index LABELLISATIONP1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index LABELLISATIONI2 rebuild
TABLESPACE %INDEX_TBS%;

Alter index JUSTIFICATIONSTATUT rebuild
TABLESPACE %INDEX_TBS%;

Alter index JUSTIFICATIONP1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index FICHE_LINKSP1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index FACTEURP1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index FACTEUR_CRITEREP1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index FACTEUR_BLINEP1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index FACTEUR_BLINEI7 rebuild
TABLESPACE %INDEX_TBS%;

Alter index FACTEUR_BLINEI6 rebuild
TABLESPACE %INDEX_TBS%;

Alter index FACTEUR_BLINEI5 rebuild
TABLESPACE %INDEX_TBS%;

Alter index FACTEUR_BLINEI4 rebuild
TABLESPACE %INDEX_TBS%;

Alter index FACTEUR_BLINEI3 rebuild
TABLESPACE %INDEX_TBS%;

Alter index FACTEUR_BLINEI2 rebuild
TABLESPACE %INDEX_TBS%;

Alter index ELT_LINKSP1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index ELT_LINKSI3 rebuild
TABLESPACE %INDEX_TBS%;

Alter index ELT_LINKSI2 rebuild
TABLESPACE %INDEX_TBS%;

Alter index ELTPACKTYPEIDX rebuild
TABLESPACE %INDEX_TBS%;

Alter index ELTLIBIDX rebuild
TABLESPACE %INDEX_TBS%;

Alter index ELTDESCIDX rebuild
TABLESPACE %INDEX_TBS%;

Alter index ELTMAINELTIDX rebuild
TABLESPACE %INDEX_TBS%;

Alter index ELEMENTP1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index ELEMENTI4 rebuild
TABLESPACE %INDEX_TBS%;

Alter index ELEMENTI3 rebuild
TABLESPACE %INDEX_TBS%;

Alter index ELEMENTI2 rebuild
TABLESPACE %INDEX_TBS%;

Alter index DROITSP1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index DROITSI3 rebuild
TABLESPACE %INDEX_TBS%;

Alter index DROITSI2 rebuild
TABLESPACE %INDEX_TBS%;

Alter index DROITSI1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index DIALECTEP1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index DIALECTEI2 rebuild
TABLESPACE %INDEX_TBS%;

Alter index CRITERE_USAGEP1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index CRITEREP1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index CRITERE_BLINEP1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index CRITERE_BLINEI8 rebuild
TABLESPACE %INDEX_TBS%;

Alter index CRITERE_BLINEI7 rebuild
TABLESPACE %INDEX_TBS%;

Alter index CRITERE_BLINEI6 rebuild
TABLESPACE %INDEX_TBS%;

Alter index CRITERE_BLINEI5 rebuild
TABLESPACE %INDEX_TBS%;

Alter index CRITERE_BLINEI4 rebuild
TABLESPACE %INDEX_TBS%;

Alter index CRITERE_BLINEI3 rebuild
TABLESPACE %INDEX_TBS%;

Alter index CRITERE_BLINEI2 rebuild
TABLESPACE %INDEX_TBS%;

Alter index CRITERE_BLINEI1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index CATEGORIEP1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index BLOBTABLEP1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index BASELINEP1 rebuild
TABLESPACE %INDEX_TBS%;

Alter index BASELINEI2 rebuild
TABLESPACE %INDEX_TBS%;

Alter index ARCHI_LINKP1 rebuild
TABLESPACE %INDEX_TBS%;

