/* Generated By:JJTree: Do not edit this line. ASTAttributeValue.java */

package com.compuware.carscode.jspparser;

public class ASTAttributeValue extends SimpleNode {
    public ASTAttributeValue(int id) {
        super(id);
    }

    public ASTAttributeValue(JspParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(JspParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
