/* Generated By:JJTree: Do not edit this line. ASTElExpression.java */

package com.compuware.carscode.jspparser;

public class ASTElExpression extends SimpleNode {
    public ASTElExpression(int id) {
        super(id);
    }

    public ASTElExpression(JspParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(JspParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
