/* Generated By:JJTree: Do not edit this line. ASTValueBinding.java */

package com.compuware.carscode.jspparser;

public class ASTValueBinding extends SimpleNode {
    public ASTValueBinding(int id) {
        super(id);
    }

    public ASTValueBinding(JspParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(JspParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
