@COBOL_PHOENIX_V1\USAGE.dat;
@COBOL_PHOENIX_V1\CRITERE_USAGE.dat;
@COBOL_PHOENIX_V1\FACTEUR_CRITERE.dat;
@COBOL_PHOENIX_V1\REGLE.dat;

-- Phoenix specific criteria
@COBOL_PHOENIX_V1\CRITERE.dat;
-- Phoenix specific metrics
@COBOL_PHOENIX_V1\METRIQUE.dat;
