/* Generated By:JJTree&JavaCC: Do not edit this line. UnifaceParserConstants.java */
/*
Beware : continuation markers (aka "%\") should be removed before parsing
         as they will not be handled by this grammar.
         In the context of Proc code compiling,
         this special construct is handled by some pre-processing,
         before actual compilation occurs.
*/

package com.compuware.pmd.uniface.ast;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface UnifaceParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BR = 3;
  /** RegularExpression Id. */
  int COMMA = 4;
  /** RegularExpression Id. */
  int COLON = 5;
  /** RegularExpression Id. */
  int SEMICOLON = 6;
  /** RegularExpression Id. */
  int DOLLAR = 7;
  /** RegularExpression Id. */
  int LPAREN = 8;
  /** RegularExpression Id. */
  int RPAREN = 9;
  /** RegularExpression Id. */
  int LBRACKET = 10;
  /** RegularExpression Id. */
  int RBRACKET = 11;
  /** RegularExpression Id. */
  int AT = 12;
  /** RegularExpression Id. */
  int UNDERSCORE = 13;
  /** RegularExpression Id. */
  int DOT = 14;
  /** RegularExpression Id. */
  int MULTIPLY = 15;
  /** RegularExpression Id. */
  int DIVIDE = 16;
  /** RegularExpression Id. */
  int MODULO = 17;
  /** RegularExpression Id. */
  int PLUS = 18;
  /** RegularExpression Id. */
  int MINUS = 19;
  /** RegularExpression Id. */
  int COMPUTE = 20;
  /** RegularExpression Id. */
  int EQUAL = 21;
  /** RegularExpression Id. */
  int LT = 22;
  /** RegularExpression Id. */
  int GT = 23;
  /** RegularExpression Id. */
  int EQ = 24;
  /** RegularExpression Id. */
  int LE = 25;
  /** RegularExpression Id. */
  int GE = 26;
  /** RegularExpression Id. */
  int NE = 27;
  /** RegularExpression Id. */
  int PLUSASSIGN = 28;
  /** RegularExpression Id. */
  int MINUSASSIGN = 29;
  /** RegularExpression Id. */
  int STARASSIGN = 30;
  /** RegularExpression Id. */
  int SLASHASSIGN = 31;
  /** RegularExpression Id. */
  int REMASSIGN = 32;
  /** RegularExpression Id. */
  int NOT = 33;
  /** RegularExpression Id. */
  int OR = 34;
  /** RegularExpression Id. */
  int AND = 35;
  /** RegularExpression Id. */
  int COMMENT = 36;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 37;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 38;
  /** RegularExpression Id. */
  int HEX_LITERAL = 39;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 40;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 41;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 42;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 43;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 44;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 45;
  /** RegularExpression Id. */
  int SYNTAX_STRING_LITERAL = 46;
  /** RegularExpression Id. */
  int STRING_LITERAL = 47;
  /** RegularExpression Id. */
  int PARAMS = 48;
  /** RegularExpression Id. */
  int ENDPARAMS = 49;
  /** RegularExpression Id. */
  int VARIABLES = 50;
  /** RegularExpression Id. */
  int ENDVARIABLES = 51;
  /** RegularExpression Id. */
  int IF = 52;
  /** RegularExpression Id. */
  int ELSEIF = 53;
  /** RegularExpression Id. */
  int ELSE = 54;
  /** RegularExpression Id. */
  int ENDIF = 55;
  /** RegularExpression Id. */
  int WHILE = 56;
  /** RegularExpression Id. */
  int ENDWHILE = 57;
  /** RegularExpression Id. */
  int REPEAT = 58;
  /** RegularExpression Id. */
  int UNTIL = 59;
  /** RegularExpression Id. */
  int SELECTCASE = 60;
  /** RegularExpression Id. */
  int CASE = 61;
  /** RegularExpression Id. */
  int ELSECASE = 62;
  /** RegularExpression Id. */
  int ENDSELECTCASE = 63;
  /** RegularExpression Id. */
  int BOOLEAN = 64;
  /** RegularExpression Id. */
  int DATE = 65;
  /** RegularExpression Id. */
  int DATETIME = 66;
  /** RegularExpression Id. */
  int FLOAT = 67;
  /** RegularExpression Id. */
  int HANDLE = 68;
  /** RegularExpression Id. */
  int IMAGE = 69;
  /** RegularExpression Id. */
  int LINEARDATE = 70;
  /** RegularExpression Id. */
  int LINEARDATETIME = 71;
  /** RegularExpression Id. */
  int LINEARTIME = 72;
  /** RegularExpression Id. */
  int NUMERIC = 73;
  /** RegularExpression Id. */
  int RAW = 74;
  /** RegularExpression Id. */
  int STRING = 75;
  /** RegularExpression Id. */
  int TIME = 76;
  /** RegularExpression Id. */
  int ANY = 77;
  /** RegularExpression Id. */
  int ENTITY = 78;
  /** RegularExpression Id. */
  int OCCURRENCE = 79;
  /** RegularExpression Id. */
  int XMLSTREAM = 80;
  /** RegularExpression Id. */
  int FUNCTION = 81;
  /** RegularExpression Id. */
  int DELETEINSTANCE = 82;
  /** RegularExpression Id. */
  int NEWINSTANCE = 83;
  /** RegularExpression Id. */
  int SETFORMFOCUS = 84;
  /** RegularExpression Id. */
  int ENTITYCOPY = 85;
  /** RegularExpression Id. */
  int ADDMONTHS = 86;
  /** RegularExpression Id. */
  int COMPARE = 87;
  /** RegularExpression Id. */
  int DISPLAYLENGTH = 88;
  /** RegularExpression Id. */
  int LENGTH = 89;
  /** RegularExpression Id. */
  int LOWERCASE = 90;
  /** RegularExpression Id. */
  int RESET = 91;
  /** RegularExpression Id. */
  int SCAN = 92;
  /** RegularExpression Id. */
  int SET = 93;
  /** RegularExpression Id. */
  int STRIPATTRIBUTES = 94;
  /** RegularExpression Id. */
  int UPPERCASE = 95;
  /** RegularExpression Id. */
  int CLOSE = 96;
  /** RegularExpression Id. */
  int COMMIT = 97;
  /** RegularExpression Id. */
  int OPEN = 98;
  /** RegularExpression Id. */
  int ROLLBACK = 99;
  /** RegularExpression Id. */
  int SQL = 100;
  /** RegularExpression Id. */
  int ACTIVATE = 101;
  /** RegularExpression Id. */
  int APEXIT = 102;
  /** RegularExpression Id. */
  int APSTART = 103;
  /** RegularExpression Id. */
  int BREAK = 104;
  /** RegularExpression Id. */
  int DISPLAY = 105;
  /** RegularExpression Id. */
  int DONE = 106;
  /** RegularExpression Id. */
  int EDIT = 107;
  /** RegularExpression Id. */
  int EXIT = 108;
  /** RegularExpression Id. */
  int GOTO = 109;
  /** RegularExpression Id. */
  int MACRO = 110;
  /** RegularExpression Id. */
  int PERFORM = 111;
  /** RegularExpression Id. */
  int PULLDOWN = 112;
  /** RegularExpression Id. */
  int RETURN = 113;
  /** RegularExpression Id. */
  int RUN = 114;
  /** RegularExpression Id. */
  int SPAWN = 115;
  /** RegularExpression Id. */
  int CLRMESS = 116;
  /** RegularExpression Id. */
  int ASKMESS = 117;
  /** RegularExpression Id. */
  int MESSAGE = 118;
  /** RegularExpression Id. */
  int PUTMESS = 119;
  /** RegularExpression Id. */
  int DEBUG = 120;
  /** RegularExpression Id. */
  int IN = 121;
  /** RegularExpression Id. */
  int OUT = 122;
  /** RegularExpression Id. */
  int INOUT = 123;
  /** RegularExpression Id. */
  int SYNC_SWITCH = 124;
  /** RegularExpression Id. */
  int ASYNC_SWITCH = 125;
  /** RegularExpression Id. */
  int ATTACHED_SWITCH = 126;
  /** RegularExpression Id. */
  int PREVIOUS_SWITCH = 127;
  /** RegularExpression Id. */
  int NEXT_SWITCH = 128;
  /** RegularExpression Id. */
  int PRINT_SWITCH = 129;
  /** RegularExpression Id. */
  int INIT_SWITCH = 130;
  /** RegularExpression Id. */
  int LIST_SWITCH = 131;
  /** RegularExpression Id. */
  int STATELESS_SWITCH = 132;
  /** RegularExpression Id. */
  int MENU_SWITCH = 133;
  /** RegularExpression Id. */
  int FROM = 134;
  /** RegularExpression Id. */
  int IDENTIFIER = 135;
  /** RegularExpression Id. */
  int LETTER = 136;
  /** RegularExpression Id. */
  int DIGIT = 137;
  /** RegularExpression Id. */
  int REGISTER = 138;
  /** RegularExpression Id. */
  int GLOBALVARIABLE = 139;
  /** RegularExpression Id. */
  int COMPONENTVARIABLE = 140;
  /** RegularExpression Id. */
  int CMPSTATEMANAGEDBY = 141;
  /** RegularExpression Id. */
  int COMPONENTNAME = 142;
  /** RegularExpression Id. */
  int COMPONENTTYPE = 143;
  /** RegularExpression Id. */
  int ENTNAME = 144;
  /** RegularExpression Id. */
  int FIELDNAME = 145;
  /** RegularExpression Id. */
  int LIBRARYNAME = 146;
  /** RegularExpression Id. */
  int MODELNAME = 147;
  /** RegularExpression Id. */
  int TABLENAME = 148;
  /** RegularExpression Id. */
  int TRIGGERABBR = 149;
  /** RegularExpression Id. */
  int ANYTHING_ELSE = 150;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<BR>",
    "\",\"",
    "\":\"",
    "\";\"",
    "\"$\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"@\"",
    "\"_\"",
    "\".\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"+\"",
    "\"-\"",
    "\"compute\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"!\"",
    "\"|\"",
    "\"&\"",
    "<COMMENT>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<SYNTAX_STRING_LITERAL>",
    "<STRING_LITERAL>",
    "\"params\"",
    "\"endparams\"",
    "\"variables\"",
    "\"endvariables\"",
    "\"if\"",
    "\"elseif\"",
    "\"else\"",
    "\"endif\"",
    "\"while\"",
    "\"endwhile\"",
    "\"repeat\"",
    "\"until\"",
    "\"selectcase\"",
    "\"case\"",
    "\"elsecase\"",
    "\"endselectcase\"",
    "\"boolean\"",
    "\"date\"",
    "\"datetime\"",
    "\"float\"",
    "\"handle\"",
    "\"image\"",
    "\"lineardate\"",
    "\"lineardatetime\"",
    "\"lineartime\"",
    "\"numeric\"",
    "\"raw\"",
    "\"string\"",
    "\"time\"",
    "\"any\"",
    "\"entity\"",
    "\"occurrence\"",
    "\"xmlstream\"",
    "<FUNCTION>",
    "\"deleteinstance\"",
    "\"newinstance\"",
    "\"setformfocus\"",
    "\"entitycopy\"",
    "\"addmonths\"",
    "\"compare\"",
    "\"displaylength\"",
    "\"length\"",
    "\"lowercase\"",
    "\"reset\"",
    "\"scan\"",
    "\"set\"",
    "\"stripattributes\"",
    "\"uppercase\"",
    "\"close\"",
    "\"commit\"",
    "\"open\"",
    "\"rollback\"",
    "\"sql\"",
    "\"activate\"",
    "\"apexit\"",
    "\"apstart\"",
    "\"break\"",
    "\"display\"",
    "\"done\"",
    "\"edit\"",
    "\"exit\"",
    "\"goto\"",
    "\"macro\"",
    "\"perform\"",
    "\"pulldown\"",
    "\"return\"",
    "\"run\"",
    "\"spawn\"",
    "\"clrmess\"",
    "\"askmess\"",
    "\"message\"",
    "\"putmess\"",
    "\"debug\"",
    "\"in\"",
    "\"out\"",
    "\"inout\"",
    "\"/sync\"",
    "\"/async\"",
    "\"/attached\"",
    "\"/previous\"",
    "\"/next\"",
    "\"/print\"",
    "\"/init\"",
    "\"/list\"",
    "\"/stateless\"",
    "\"/menu\"",
    "\"from\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<REGISTER>",
    "<GLOBALVARIABLE>",
    "<COMPONENTVARIABLE>",
    "\"<$cmpStateManagedBy>\"",
    "\"<$componentName>\"",
    "\"<$componentType>\"",
    "\"<$entName>\"",
    "\"<$fieldName>\"",
    "\"<$libraryName>\"",
    "\"<$modelName>\"",
    "\"<$tableName>\"",
    "\"<$triggerAbbr>\"",
    "<ANYTHING_ELSE>",
  };

}
