/* Generated By:JavaCC: Do not edit this line. UnifaceParserTreeConstants.java Version 5.0 */
package com.compuware.pmd.uniface.ast;

public interface UnifaceParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTARGUMENT = 1;
  public int JJTEXPRESSION = 2;
  public int JJTCOMPILETIMECONSTANT = 3;
  public int JJTCONSTANT = 4;
  public int JJTEXPRESSIONLIST = 5;
  public int JJTLOGICALEXPRESSION = 6;
  public int JJTRELATIONALEXPRESSION = 7;
  public int JJTADDITIVEEXPRESSION = 8;
  public int JJTMULTIPLICATIVEEXPRESSION = 9;
  public int JJTUNARYEXPRESSION = 10;
  public int JJTUSERDEFINEDFUNCTION = 11;
  public int JJTSTRING = 12;
  public int JJTIDENTIFIER = 13;
  public int JJTREGISTER = 14;
  public int JJTGLOBALVARIABLE = 15;
  public int JJTCOMPONENTVARIABLE = 16;
  public int JJTIDENTIFIERLIST = 17;
  public int JJTINTEGER = 18;
  public int JJTDATATYPE = 19;
  public int JJTDIRECTION = 20;
  public int JJTVARIABLEDEFINITION = 21;
  public int JJTPARAMETER = 22;
  public int JJTPARAMETERBLOCK = 23;
  public int JJTVARIABLEBLOCK = 24;
  public int JJTCOMMENT = 25;
  public int JJTCOMMENTLINE = 26;
  public int JJTINSTRUCTION = 27;
  public int JJTPROCSTATEMENT = 28;
  public int JJTINDIRECTION = 29;
  public int JJTCOMPUTE = 30;
  public int JJTASSIGNMENT = 31;
  public int JJTFUNCTION = 32;
  public int JJTIFSTATEMENT = 33;
  public int JJTWHILESTATEMENT = 34;
  public int JJTREPEATSTATEMENT = 35;
  public int JJTSELECTCASESTATEMENT = 36;
  public int JJTLABELSTATEMENT = 37;
  public int JJTSTATEMENT = 38;
  public int JJTRETURNSTATEMENT = 39;
  public int JJTDELETEINSTANCESTATEMENT = 40;
  public int JJTNEWINSTANCESTATEMENT = 41;
  public int JJTSETFORMFOCUSSTATEMENT = 42;
  public int JJTENTITYCOPYSTATEMENT = 43;
  public int JJTADDMONTHSSTATEMENT = 44;
  public int JJTCOMPARESTATEMENT = 45;
  public int JJTDISPLAYLENGTHSTATEMENT = 46;
  public int JJTLENGTHSTATEMENT = 47;
  public int JJTLOWERCASESTATEMENT = 48;
  public int JJTRESETSTATEMENT = 49;
  public int JJTSCANSTATEMENT = 50;
  public int JJTSETSTATEMENT = 51;
  public int JJTSTRIPATTRIBUTESSTATEMENT = 52;
  public int JJTUPPERCASESTATEMENT = 53;
  public int JJTCLOSESTATEMENT = 54;
  public int JJTCOMMITSTATEMENT = 55;
  public int JJTOPENSTATEMENT = 56;
  public int JJTROLLBACKSTATEMENT = 57;
  public int JJTSQLSTATEMENT = 58;
  public int JJTACTIVATESTATEMENT = 59;
  public int JJTDISPLAYSTATEMENT = 60;
  public int JJTGOTOSTATEMENT = 61;
  public int JJTCLRMESSSTATEMENT = 62;
  public int JJTDEBUGSTATEMENT = 63;


  public String[] jjtNodeName = {
    "Start",
    "Argument",
    "Expression",
    "CompileTimeConstant",
    "Constant",
    "ExpressionList",
    "LogicalExpression",
    "RelationalExpression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "UserDefinedFunction",
    "String",
    "Identifier",
    "Register",
    "GlobalVariable",
    "ComponentVariable",
    "IdentifierList",
    "Integer",
    "Datatype",
    "Direction",
    "VariableDefinition",
    "Parameter",
    "ParameterBlock",
    "VariableBlock",
    "Comment",
    "CommentLine",
    "Instruction",
    "ProcStatement",
    "Indirection",
    "Compute",
    "Assignment",
    "Function",
    "IfStatement",
    "WhileStatement",
    "RepeatStatement",
    "SelectCaseStatement",
    "LabelStatement",
    "Statement",
    "ReturnStatement",
    "DeleteinstanceStatement",
    "NewinstanceStatement",
    "SetformfocusStatement",
    "EntitycopyStatement",
    "AddmonthsStatement",
    "CompareStatement",
    "DisplaylengthStatement",
    "LengthStatement",
    "LowercaseStatement",
    "ResetStatement",
    "ScanStatement",
    "SetStatement",
    "StripattributesStatement",
    "UppercaseStatement",
    "CloseStatement",
    "CommitStatement",
    "OpenStatement",
    "RollbackStatement",
    "SqlStatement",
    "ActivateStatement",
    "DisplayStatement",
    "GotoStatement",
    "ClrmessStatement",
    "DebugStatement",
  };
}
/* JavaCC - OriginalChecksum=b3548de67352d94db5b47d81b3327144 (do not edit this line) */
