Alter index USAGEP1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index TYPE_METRIQUEP1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index TYPE_LABELLISATIONP1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index TYPE_FICHEP1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index TYPE_ELEMENTP1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index TECHNOLOGIEP1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index SEVERITEP1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index SEUILP1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index SEUILI3 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index SEUILI2 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index REGLEP1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index REGLEI2 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index QAMETRIQUEP1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index QAMETRIQUEI5 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index QAMETRIQUEI4 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index QAMETRIQUEI3 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index QAMETRIQUEI2 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index PROJETP1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index PROJETI2 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index PRIMARYKEY rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index POIDS_FACT_CRITP1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index POIDS_FACT_CRITI6 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index POIDS_FACT_CRITI5 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index POIDS_FACT_CRITI4 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index POIDS_FACT_CRITI3 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index POIDS_FACT_CRITI2 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index POIDS_FACT_CRITI1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index PACKAGEP1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index PACKAGEI3 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index PACKAGEI2 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index OUTILSP1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index NIVEAUP1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index METRIQUEP1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index METRIQUEI5 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index METRIQUEI4 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index METRIQUEI2 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index LINK_REAL_PK11037977519508 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index LINK_REALI1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index LINK_ELT_BLIN_PK11037977427967 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index LINK_ELT_BLINEI1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index LANGAGEP1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index LABELLISATIONP1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index LABELLISATIONI2 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index JUSTIFICATIONSTATUT rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index JUSTIFICATIONP1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index FICHE_LINKSP1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index FACTEURP1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index FACTEUR_CRITEREP1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index FACTEUR_BLINEP1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index FACTEUR_BLINEI7 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index FACTEUR_BLINEI6 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index FACTEUR_BLINEI5 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index FACTEUR_BLINEI4 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index FACTEUR_BLINEI3 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index FACTEUR_BLINEI2 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index ELTPACKTYPEIDX rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index ELT_LINKSP1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index ELT_LINKSI3 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index ELT_LINKSI2 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index ELTLIBIDX rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index ELTDESCIDX rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index ELEMENT_TYPE_DESC rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index ELEMENTP1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index ELEMENTI4 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index ELEMENTI3 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index ELEMENTI2 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index DROITSP1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index DROITSI3 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index DROITSI2 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index DROITSI1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index DIALECTEP1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index DIALECTEI2 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index CRITERE_USAGEP1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index CRITEREP1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index CRITERE_BLINEP1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index CRITERE_BLINEI8 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index CRITERE_BLINEI7 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index CRITERE_BLINEI6 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index CRITERE_BLINEI5 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index CRITERE_BLINEI4 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index CRITERE_BLINEI3 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index CRITERE_BLINEI2 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index CRITERE_BLINEI1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index CATEGORIEP1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index BLOBTABLEP1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index BASELINEP1 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index BASELINEI2 rebuild
TABLESPACE TBS_USERS_INDEX;

Alter index ARCHI_LINKP1 rebuild
TABLESPACE TBS_USERS_INDEX;

