package com.compuware.caqs.pmd.php;
/* Generated By:JJTree: Do not edit this line. ASTBitwiseAndExpression.java */

public class ASTBitwiseAndExpression extends SimpleNode {
  public ASTBitwiseAndExpression(int id) {
    super(id);
  }

  public ASTBitwiseAndExpression(PHPparser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
