package com.compuware.caqs.pmd.php;
/* Generated By:JJTree: Do not edit this line. ASTBitwiseXorExpression.java */

public class ASTBitwiseXorExpression extends SimpleNode {
  public ASTBitwiseXorExpression(int id) {
    super(id);
  }

  public ASTBitwiseXorExpression(PHPparser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
