package com.compuware.caqs.pmd.php;
/* Generated By:JJTree: Do not edit this line. ASTConstant.java */

public class ASTConstant extends SimpleNode {
  public ASTConstant(int id) {
    super(id);
  }

  public ASTConstant(PHPparser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
