package com.compuware.caqs.pmd.php;
/* Generated By:JJTree: Do not edit this line. ASTClassMembers.java */

public class ASTClassMembers extends SimpleNode {
  public ASTClassMembers(int id) {
    super(id);
  }

  public ASTClassMembers(PHPparser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
