package com.compuware.caqs.pmd.php;
/* Generated By:JJTree: Do not edit this line. ASTClassInstantiation.java */

public class ASTClassInstantiation extends SimpleNode {
  public ASTClassInstantiation(int id) {
    super(id);
  }

  public ASTClassInstantiation(PHPparser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
