package com.compuware.caqs.pmd.php;
/* Generated By:JJTree: Do not edit this line. ASTDoubleStringLiteral.java */

public class ASTDoubleStringLiteral extends SimpleNode {
  public ASTDoubleStringLiteral(int id) {
    super(id);
  }

  public ASTDoubleStringLiteral(PHPparser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
