package com.compuware.caqs.pmd.php;
/* Generated By:JJTree: Do not edit this line. ASTDefineStatement.java */

public class ASTDefineStatement extends SimpleNode {
  public ASTDefineStatement(int id) {
    super(id);
  }

  public ASTDefineStatement(PHPparser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
