package com.compuware.caqs.pmd.php;
/* Generated By:JJTree: Do not edit this line. ASTEndOfStatement.java */

public class ASTEndOfStatement extends SimpleNode {
  public ASTEndOfStatement(int id) {
    super(id);
  }

  public ASTEndOfStatement(PHPparser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
