package com.compuware.caqs.pmd.php;
/* Generated By:JJTree: Do not edit this line. ASTEmbeddedHtml.java */

public class ASTEmbeddedHtml extends SimpleNode {
  public ASTEmbeddedHtml(int id) {
    super(id);
  }

  public ASTEmbeddedHtml(PHPparser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
