package com.compuware.caqs.pmd.php;
/* Generated By:JJTree: Do not edit this line. ASTHtmlBlock.java */

public class ASTHtmlBlock extends SimpleNode {
  public ASTHtmlBlock(int id) {
    super(id);
  }

  public ASTHtmlBlock(PHPparser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
