package com.compuware.caqs.pmd.php;
/* Generated By:JJTree: Do not edit this line. ASTInstanceOfExpression.java */

public class ASTInstanceOfExpression extends SimpleNode {
  public ASTInstanceOfExpression(int id) {
    super(id);
  }

  public ASTInstanceOfExpression(PHPparser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
