package com.compuware.caqs.pmd.php;
/* Generated By:JJTree: Do not edit this line. ASTInterfaceMember.java */

public class ASTInterfaceMember extends SimpleNode {
  public ASTInterfaceMember(int id) {
    super(id);
  }

  public ASTInterfaceMember(PHPparser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
