package com.compuware.caqs.pmd.php;
/* Generated By:JJTree: Do not edit this line. ASTIncludeStatement.java */

public class ASTIncludeStatement extends SimpleNode {
  public ASTIncludeStatement(int id) {
    super(id);
  }

  public ASTIncludeStatement(PHPparser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
