package com.compuware.caqs.pmd.php;
/* Generated By:JJTree: Do not edit this line. ASTInterfaceMembers.java */

public class ASTInterfaceMembers extends SimpleNode {
  public ASTInterfaceMembers(int id) {
    super(id);
  }

  public ASTInterfaceMembers(PHPparser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
