package com.compuware.caqs.pmd.php;
/* Generated By:JJTree: Do not edit this line. ASTLogicalTextAndExpression.java */

public class ASTLogicalTextAndExpression extends SimpleNode {
  public ASTLogicalTextAndExpression(int id) {
    super(id);
  }

  public ASTLogicalTextAndExpression(PHPparser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
