package com.compuware.caqs.pmd.php;
/* Generated By:JJTree: Do not edit this line. ASTLogical_And_Expression.java */

public class ASTLogical_And_Expression extends SimpleNode {
  public ASTLogical_And_Expression(int id) {
    super(id);
  }

  public ASTLogical_And_Expression(PHPparser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
