package com.compuware.caqs.pmd.php;
/* Generated By:JJTree: Do not edit this line. ASTLogicalTextXorExpression.java */

public class ASTLogicalTextXorExpression extends SimpleNode {
  public ASTLogicalTextXorExpression(int id) {
    super(id);
  }

  public ASTLogicalTextXorExpression(PHPparser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
