package com.compuware.caqs.pmd.php;
/* Generated By:JJTree: Do not edit this line. ASTLogicalTextOrExpression.java */

public class ASTLogicalTextOrExpression extends SimpleNode {
  public ASTLogicalTextOrExpression(int id) {
    super(id);
  }

  public ASTLogicalTextOrExpression(PHPparser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
