package com.compuware.caqs.pmd.php;
/* Generated By:JJTree: Do not edit this line. ASTMemberDeclaration.java */

public class ASTMemberDeclaration extends SimpleNode {
  public ASTMemberDeclaration(int id) {
    super(id);
  }

  public ASTMemberDeclaration(PHPparser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
