package com.compuware.caqs.pmd.php;
/* Generated By:JJTree: Do not edit this line. ASTParameterList.java */

public class ASTParameterList extends SimpleNode {
  public ASTParameterList(int id) {
    super(id);
  }

  public ASTParameterList(PHPparser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
