package com.compuware.caqs.pmd.php;
/* Generated By:JJTree: Do not edit this line. ASTPhpPage.java */

public class ASTPhpPage extends SimpleNode {
  public ASTPhpPage(int id) {
    super(id);
  }

  public ASTPhpPage(PHPparser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
