package com.compuware.caqs.pmd.php;
/* Generated By:JJTree: Do not edit this line. ASTPostfixIncDecExpression.java */

public class ASTPostfixIncDecExpression extends SimpleNode {
  public ASTPostfixIncDecExpression(int id) {
    super(id);
  }

  public ASTPostfixIncDecExpression(PHPparser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
