package com.compuware.caqs.pmd.php;

/* Generated By:JJTree: Do not edit this line. D:\Prof\Data\tools\javacc-4.0\javacc-4.0\examples\PHPGrammar\PHPTreeConstants.java */

public interface PHPTreeConstants
{
  public int JJTPHPPAGE = 0;
  public int JJTHTMLBLOCK = 1;
  public int JJTSTATEMENT = 2;
  public int JJTTHROWSTATEMENT = 3;
  public int JJTTRYBLOCK = 4;
  public int JJTENDOFSTATEMENT = 5;
  public int JJTEMBEDDEDHTML = 6;
  public int JJTDEFINESTATEMENT = 7;
  public int JJTLABELEDSTATEMENT = 8;
  public int JJTEXPRESSIONSTATEMENT = 9;
  public int JJTCOMPOUNDSTATEMENT = 10;
  public int JJTSELECTIONSTATEMENT = 11;
  public int JJTITERATIONSTATEMENT = 12;
  public int JJTJUMPSTATEMENT = 13;
  public int JJTPARAMETERLIST = 14;
  public int JJTPARAMETER = 15;
  public int JJTCLASSDECLARATION = 16;
  public int JJTCLASSMEMBERS = 17;
  public int JJTMEMBERDECLARATION = 18;
  public int JJTINTERFACEDECLARATION = 19;
  public int JJTINTERFACEMEMBERS = 20;
  public int JJTINTERFACEMEMBER = 21;
  public int JJTINCLUDESTATEMENT = 22;
  public int JJTECHOSTATEMENT = 23;
  public int JJTEXPRESSION = 24;
  public int JJTLOGICALTEXTOREXPRESSION = 25;
  public int JJTLOGICALTEXTXOREXPRESSION = 26;
  public int JJTLOGICALTEXTANDEXPRESSION = 27;
  public int JJTASSIGNMENTEXPRESSION = 28;
  public int JJTASSIGNMENTOPERATOR = 29;
  public int JJTCONDITIONALEXPRESSION = 30;
  public int JJTLOGICAL_OR_EXPRESSION = 31;
  public int JJTLOGICAL_AND_EXPRESSION = 32;
  public int JJTBITWISEOREXPRESSION = 33;
  public int JJTBITWISEXOREXPRESSION = 34;
  public int JJTBITWISEANDEXPRESSION = 35;
  public int JJTEQUALITYEXPRESSION = 36;
  public int JJTRELATIONALEXPRESSION = 37;
  public int JJTSHIFTEXPRESSION = 38;
  public int JJTADDITIVEEXPRESSION = 39;
  public int JJTMULTIPLICATIVEEXPRESSION = 40;
  public int JJTCASTEXPRESSION = 41;
  public int JJTUNARYEXPRESSION = 42;
  public int JJTPREFIXINCDECEXPRESSION = 43;
  public int JJTPOSTFIXINCDECEXPRESSION = 44;
  public int JJTINSTANCEOFEXPRESSION = 45;
  public int JJTPOSTFIXEXPRESSION = 46;
  public int JJTPRIMARYEXPRESSION = 47;
  public int JJTARRAY = 48;
  public int JJTCLASSINSTANTIATION = 49;
  public int JJTVARIABLE = 50;
  public int JJTARGUMENTEXPRESSIONLIST = 51;
  public int JJTCONSTANT = 52;
  public int JJTSTRING = 53;
  public int JJTDOUBLESTRINGLITERAL = 54;
  public int JJTVISIBILITY = 55;


  public String[] jjtNodeName = {
    "PhpPage",
    "HtmlBlock",
    "Statement",
    "ThrowStatement",
    "TryBlock",
    "EndOfStatement",
    "EmbeddedHtml",
    "DefineStatement",
    "LabeledStatement",
    "ExpressionStatement",
    "CompoundStatement",
    "SelectionStatement",
    "IterationStatement",
    "JumpStatement",
    "ParameterList",
    "Parameter",
    "ClassDeclaration",
    "ClassMembers",
    "MemberDeclaration",
    "InterfaceDeclaration",
    "InterfaceMembers",
    "InterfaceMember",
    "IncludeStatement",
    "EchoStatement",
    "Expression",
    "LogicalTextOrExpression",
    "LogicalTextXorExpression",
    "LogicalTextAndExpression",
    "AssignmentExpression",
    "AssignmentOperator",
    "ConditionalExpression",
    "Logical_Or_Expression",
    "Logical_And_Expression",
    "BitwiseOrExpression",
    "BitwiseXorExpression",
    "BitwiseAndExpression",
    "EqualityExpression",
    "RelationalExpression",
    "ShiftExpression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "CastExpression",
    "UnaryExpression",
    "PrefixIncDecExpression",
    "PostfixIncDecExpression",
    "InstanceOfExpression",
    "PostfixExpression",
    "PrimaryExpression",
    "Array",
    "ClassInstantiation",
    "Variable",
    "ArgumentExpressionList",
    "Constant",
    "String",
    "DoubleStringLiteral",
    "Visibility",
  };
}
