-- Splint criteria
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_FORMAT');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_ABSTRACT');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_ALIASING_MEMORY');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_ALLUSE_EXPORT');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_ALLUSE_PARAMETERS');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_ALLUSE');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_BOOLEANS_HELP');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_BOOLEANS_OPERATIONS');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_BOOLEANS_POINTERS');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_BOOLEANS_PREDICATES');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_COMMENTS');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_COMPLETE_SPECIFICATIONS');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_CONTROLFLOW_MEMORY');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_CONTROLFLOW');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_DECLARATIONS_LIBRARIES');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_DECLARATIONS');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_DEFINITION');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_EFFECT_CONTROLFLOW');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_EXTENSIBLE_MEMORY');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_ITERATORS');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_LIBRARIES_ANSI');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_MEMORY_DEFINITION');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_MEMORY_IMPLICIT');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_MEMORY_LEAKS');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_MEMORY_RELEASED');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_MEMORY');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_MEMORYBOUNDS_MEMORY');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_MODIFICATION_SPECIFICATIONS');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_NAMES_ANSI');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_NAMES_PREFIXES');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_NAMES');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_NULL_MEMORY');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_OPERATIONS_POINTERS');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_OPERATIONS');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_RETURNVALS_BOOLEANS');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_RETURNVALS');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_SYSTEMFUNCTIONS_UNDEFINED');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_SYSTEMFUNCTIONS');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_TYPEEQUIVALENCE_POINTERS');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_TYPEEQUIVALENCE');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_TYPEMISMATCH');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_UNDEFINED_ANSI');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_UNRECOGNIZED_DISPLAY');
INSERT INTO CRITERE (ID_CRIT) VALUES ('SPLINT_WARNUSE_SECURITY');


-- CppCheck criteria

INSERT INTO CRITERE (ID_CRIT) VALUES ('CPPCHECK_AUTOVARIABLES');
INSERT INTO CRITERE (ID_CRIT) VALUES ('CPPCHECK_BUFFEROVERRUN');
INSERT INTO CRITERE (ID_CRIT) VALUES ('CPPCHECK_CLASS');
INSERT INTO CRITERE (ID_CRIT) VALUES ('CPPCHECK_DANGEROUSFUNCTIONS');
INSERT INTO CRITERE (ID_CRIT) VALUES ('CPPCHECK_EXCEPTIONSAFETY');
INSERT INTO CRITERE (ID_CRIT) VALUES ('CPPCHECK_MISC');
INSERT INTO CRITERE (ID_CRIT) VALUES ('CPPCHECK_STL');
INSERT INTO CRITERE (ID_CRIT) VALUES ('CPPCHECK_MEMORYLEAK');
INSERT INTO CRITERE (ID_CRIT) VALUES ('CPPCHECK_DEADCODE');


commit;

