INSERT INTO OUTILS (ID_OUTILS,LIB_OUTILS) VALUES ('SPLINT','Splint');
INSERT INTO OUTILS (ID_OUTILS,LIB_OUTILS) VALUES ('PMCCABE','PMcCabe');
INSERT INTO OUTILS (ID_OUTILS,LIB_OUTILS) VALUES ('CPPCHECK','CppCheck');
INSERT INTO OUTILS (ID_OUTILS,LIB_OUTILS) VALUES ('FLAWFINDER','FlawFinder');

commit;

