
package com.compuware.caqs.webservices.projectslist;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import org.eclipse.jface.preference.IPreferenceStore;

import com.compuware.caqs.eclipseplugin.preferences.PreferenceConstants;
import com.compuware.caqs.plugin.Activator;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProjectsListForUserWS", targetNamespace = "http://impl.webservices.caqs.compuware.com/")
public class ProjectsListForUserWS
    extends Service
{

    private final static URL PROJECTSLISTFORUSERWS_WSDL_LOCATION;
    private final static WebServiceException PROJECTSLISTFORUSERWS_EXCEPTION;
    private final static QName PROJECTSLISTFORUSERWS_QNAME = new QName("http://impl.webservices.caqs.compuware.com/", "ProjectsListForUserWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	IPreferenceStore store = Activator.getDefault().getPreferenceStore();
    		String urlHost = store.getString(PreferenceConstants.P_CAQS_URL);
            url = new URL(urlHost+"/caqs/services/ProjectsListForUserWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROJECTSLISTFORUSERWS_WSDL_LOCATION = url;
        PROJECTSLISTFORUSERWS_EXCEPTION = e;
    }

    public ProjectsListForUserWS() {
        super(__getWsdlLocation(), PROJECTSLISTFORUSERWS_QNAME);
    }

    public ProjectsListForUserWS(URL wsdlLocation) {
        super(wsdlLocation, PROJECTSLISTFORUSERWS_QNAME);
    }

    public ProjectsListForUserWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ProjectsListForUserWSImpl
     */
    @WebEndpoint(name = "ProjectsListForUserWSImplPort")
    public ProjectsListForUserWSImpl getProjectsListForUserWSImplPort() {
        return super.getPort(new QName("http://impl.webservices.caqs.compuware.com/", "ProjectsListForUserWSImplPort"), ProjectsListForUserWSImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProjectsListForUserWSImpl
     */
    @WebEndpoint(name = "ProjectsListForUserWSImplPort")
    public ProjectsListForUserWSImpl getProjectsListForUserWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.webservices.caqs.compuware.com/", "ProjectsListForUserWSImplPort"), ProjectsListForUserWSImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROJECTSLISTFORUSERWS_EXCEPTION!= null) {
            throw PROJECTSLISTFORUSERWS_EXCEPTION;
        }
        return PROJECTSLISTFORUSERWS_WSDL_LOCATION;
    }

}
