
package com.compuware.caqs.webservices.projectslist;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProjectsListForUserWSImpl", targetNamespace = "http://impl.webservices.caqs.compuware.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProjectsListForUserWSImpl {


    /**
     * 
     * @return
     *     returns java.util.List<javaapplication5.newtest2.ProjectWS>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProjectsListForUser", targetNamespace = "http://impl.webservices.caqs.compuware.com/", className = "javaapplication5.newtest2.GetProjectsListForUser")
    @ResponseWrapper(localName = "getProjectsListForUserResponse", targetNamespace = "http://impl.webservices.caqs.compuware.com/", className = "javaapplication5.newtest2.GetProjectsListForUserResponse")
    public List<ProjectWS> getProjectsListForUser();

}
