package com.compuware.caqs.pmd.cpp.ast;
/* Generated By:JJTree: Do not edit this line. ASTstorage_class_specifier.java */

public class ASTstorage_class_specifier extends SimpleNode {
  public ASTstorage_class_specifier(int id) {
    super(id);
  }

  public ASTstorage_class_specifier(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
