package com.compuware.caqs.pmd.cpp.ast;

import com.compuware.caqs.pmd.cpp.ast.CPPParserVisitor;

/* Generated By:JJTree: Do not edit this line. Node.java */

/* All AST nodes must implement this interface.  It provides basic
machinery for constructing the parent and child relationships
between nodes. */

public interface Node extends com.compuware.caqs.pmd.ast.Node {


 /**
  * Accept the visitor. *
  */
 public Object jjtAccept(CPPParserVisitor visitor, Object data);
}