
package com.compuware.caqs.webservices.projectinfos;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProjectInfosWSImpl", targetNamespace = "http://impl.webservices.caqs.compuware.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProjectInfosWSImpl {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retrieveAnalyzedSource", targetNamespace = "http://impl.webservices.caqs.compuware.com/", className = "javaapplication5.newtest5.RetrieveAnalyzedSource")
    @ResponseWrapper(localName = "retrieveAnalyzedSourceResponse", targetNamespace = "http://impl.webservices.caqs.compuware.com/", className = "javaapplication5.newtest5.RetrieveAnalyzedSourceResponse")
    public byte[] retrieveAnalyzedSource(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
